.goreleaser.yml

r? @ob-stripe 
We don't need a folder for the homebrew recipe, remove that.

Remove homebrew formula folder

---

pkg/login/client_login.go
pkg/login/client_login_test.go
pkg/login/interactive_login.go
pkg/login/login_message.go
pkg/login/login_message_test.go
pkg/login/poll.go
pkg/login/poll_test.go

r? @ob-stripe 
Client side implementation for showing customized login completion messages when a user successfully authenticates with the CLI.
There is a linked [pay-server PR](https://git.corp.stripe.com/stripe-internal/pay-server/pull/160275) to send the display name with the authentication response. This is necessary since security asked that we authenticate with restricted keys, and there is a known permissions issue that restricted keys cannot be used to access account settings. This will allow web login to show the display name if available.
If a user does interactive login, we can show the display name if they use a secret key, otherwise we show only the account ID.
Added automated tests in `login_message_test.go` and tested manually with the CLI.
[Jira …

Add customized login completion messages with user's display name

---

pkg/requests/base.go
pkg/requests/base_test.go

r? @aarongreen-stripe @brandur-stripe @tomer-stripe 
We broke support for expand parameters in #22. This fixes it.

Fix expand support

---

pkg/requests/base.go
pkg/requests/base_test.go
pkg/stripe/client.go
pkg/stripe/verbosetransport.go
pkg/stripe/verbosetransport_test.go

r? @brandur-stripe @tomer-stripe @aarongreen-stripe 
Adds a new `verboseTransport` type that acts like a regular HTTP transport but can optionally dump headers and other information (URL, status code).
This replaces the existing code in `requests/base.go` to output headers.
Behavior changes:
- headers are printed to stderr instead of stdout
- we don't print all headers, but just a few relevant ones
- API keys are redacted
- we also output the HTTP method and URL, and the response's status code

Add verbose transport

---

README.md

r? @ob-stripe 
As per https://stripe.com/docs/api/events/types, use singular `payment_intent` for event types and remove reference to `payment_intent.updated` as not currently supported.

docs: Update supported payment_intent event types

---

pkg/proxy/proxy.go
pkg/proxy/proxy_test.go

r? @aarongreen-stripe @tomer-stripe @brandur-stripe 
Truncate webhook responses so the message stays under a certain size.
Messages sent to Stripe over the websocket connection must stay under 32 KiB, otherwise the server will reply with an unclear error message ("websocket frame too large"). This PR ensures we stay under the limit:
- the `body` field is truncated to 5000 bytes
- the `headers` map is limited to 25 entries, with keys (header names) truncated to 50 bytes and values truncated to 200 bytes
Even accounting for some overhead for JSON formatting and additional attributes, this should ensure we stay well under the limit.

Truncate body and headers in webhook responses

---

pkg/requests/base.go

r? @tomer-stripe @brandur-stripe @aarongreen-stripe 
Request parameters are now stored as a field on the `Base` struct instead of a global variable in the `requests` package. This will make it easier to reuse the `Base` struct for resource commands.

Move request parameters inside Base struct

---

pkg/proxy/proxy.go
pkg/websocket/client.go
pkg/websocket/client_test.go
pkg/websocket/messages.go
pkg/websocket/messages_test.go
pkg/websocket/request_log_messages.go
pkg/websocket/webhook_messages.go
pkg/websocket/webhook_messages_test.go

r? @ob-stripe  @tomer-stripe 
In preparation for receiving request logs events from the StripeCLI API, we need to generalize the types of events that can be received, parsed, and handled from the websockets package. This is a small change that segments the different types of events into different files and introduces the 'RequestLogEvent' type.
Existing automated test + new automated test for unmarshalling request log events.

Generalize websocket event type for webhooks and request logs

---

pkg/cmd/listen.go
pkg/proxy/proxy.go
pkg/stripeauth/client.go
pkg/stripeauth/client_test.go
pkg/stripeauth/messages.go
pkg/websocket/client.go
pkg/websocket/client_test.go

r? @tomer-stripe  @ob-stripe 
Now that we want to support listening for webhook events or request log events, we need to specify to the API what type of event a websocket connection is for. The type of feature should be specified as a parameter in the authorize request as well as in the subscribe request.
Updated existing automated tests to include `websocket_feature`. Also tested manually to make sure authorization works for the appropriate feature specified.

Websocket generalization for feature specification

---

README.md
go.mod
go.sum
pkg/ansi/ansi.go
pkg/cmd/root.go
pkg/cmd/status.go
pkg/status/status.go
pkg/status/status_test.go

r? @ob-stripe @aarongreen-stripe @brandur-stripe @auchenberg-stripe 
Let people retrieve API status through the CLI. This pulls from our status site so that is the source of truth.
The command is `stripe status` and includes several flags with:
1. `--verbose`, lists out status of individual systems
2. `--format`, let's people render the status as json
3. `--poll`, continuously checks the status site
4. `--poll-rate`, let's people check more frequently than ever 60 seconds (up to 5 seconds per poll)
5. `--hide-spinner`,  hides the spinner that's shown when polling

Add status command

---

pkg/spec/spec.go

r? @ob-stripe 
According to [this comment](https://github.com/golang/go/issues/25922#issuecomment-451123151), this should let us run the `vfsgendev` without requiring it to be installed separately.

Don't require vfsgen to be installed

---

.goreleaser.yml

r? @ob-stripe @aarongreen-stripe @brandur-stripe 
Removing the `go generate` command from the go-releaser script for now to unblock releases.

Remove go generate from goreleaser/travis build

---

pkg/spec/spec.go
pkg/spec/spec_test.go

r? @ob-stripe 
Add code for parsing the OpenAPI spec into in-memory structures.
The code is largely copied from stripe-mock, with just a few additions to parse some additional attributes from the SDK variant of the spec like `x-stripeOperation`.
Self-approving because I need this to make progress on resource commands, but note that this code is not used outside of tests yet.

Add code for parsing the OpenAPI spec

---

pkg/endpoint/client.go
pkg/login/poll.go
pkg/status/status.go
pkg/stripeauth/client.go
pkg/websocket/client.go

r? @ob-stripe 
Call `resp.Body.Close()` after all HTTP requests, as reported by https://github.com/timakin/bodyclose.

Call resp.Body.Close everywhere

---

.golangci.yml
.travis.yml
.vscode/settings.json
Makefile

r? @ob-stripe  
Replace golang and govet with [GolangCI-Lint](https://github.com/golangci/golangci-lint), a pretty awesome metalinter tool.
This is basically the same setup as the one used by the GoReleaser project, except that I created a custom `.golangci.yml` configuration file to disable more linters because those would require larger changes. (I do think we should fix these issues and enable these linters, but we can do that later.)
The Makefile was updated to be very similar to GoReleaser's. Basically:
- run `make setup` to install (or update) the linter locally and download dependencies
- run `make build` (or just `make`) to compile the project and output a `stripe` executable
- run `make test` to run tests (and tests only)
- run `make cover` to run tests …

Use golangci-lint for linting

---

pkg/cmd/root.go
pkg/cmd/version.go
pkg/version/version.go

r? @ob-stripe @aarongreen-stripe @brandur-stripe 
cc @fishcharlie
Fixes #37, adds `-v` flag for version and cleans up version printing.

Add -v flag for version

---

pkg/cmd/root.go

With the present organization, `stripe --help` returns information about the `GET`, `POST`, and `DELETE` commands in a section called `API commands`, and `logs` is in its own section and feels empty all alone.
This proposes a new format for the help section, where the existing `API commands` is renamed to `HTTP commands` and there is a new `Stripe commands` section which contains the `logs` command and the `status` command.
Here's what the new help section would look like.

--help formatting

---

pkg/proxy/endpoint.go
pkg/proxy/endpoint_test.go
pkg/proxy/proxy.go

r? @aarongreen-stripe @brandur-stripe @tomer-stripe 
Merge `endpoint` package into `proxy` package. Endpoint clients are fairly specific to the webhook proxy feature. I expect this refactor will make it easier to handle different routes for Connect events.

Merge endpoint package into proxy package

---

pkg/cmd/listen.go
pkg/cmd/listen_test.go
pkg/proxy/proxy.go

r? @aarongreen-stripe @brandur-stripe @tomer-stripe 
More refactoring. This replaces `EndpointsMap` (a map of URLs to event types) with `EndpointRoutes` (a list of `EndpointRoute` which is a struct containing a URL and a list of event types).
This allows for having more than one endpoint with the same URL, which will be needed for Connect support.

Replace endpoints map with list of endpoint routes

---

pkg/cmd/listen.go
pkg/cmd/listen_test.go
pkg/proxy/endpoint.go
pkg/proxy/endpoint_test.go
pkg/proxy/proxy.go
pkg/requests/examples.go

r? @brandur-stripe @tomer-stripe @aarongreen-stripe 
Add support for forwarding Connect events to a separate endpoint, using a new `--forward-connect-to` flag. When the flag is omitted, Connect events are sent to the normal URL (i.e. same as current behavior).

Add support for forwarding Connect events to separate route

---

pkg/login/interactive_login.go

r? @ob-stripe 
I removed the conversion in #70, but it turns out that the conversion is necessary for Windows builds.

Convert syscall.Handle to int for Windows builds

---

pkg/cmd/delete.go
pkg/cmd/get.go
pkg/cmd/post.go
pkg/config/profile.go
pkg/requests/base.go
pkg/requests/examples.go

r? @ob-stripe @aarongreen-stripe @brandur-stripe 
* Fixes reading device name, this was hardcoded to `default` which caused issues for specific projects.
* Fixes profiles for http requests, this was always using `default` even if you passed in a project name.
Fixes #84 and fixes #85

Correctly read device name and profile for listen and http requests

---

pkg/cmd/listen.go
pkg/cmd/listen_test.go
pkg/cmd/trigger.go
pkg/requests/examples.go

r? @ob-stripe 
Base url was not being passed in to the webhooks endpoint load so it was always empty. I also discovered another issue in the process where `path.Join` removes all double forward slashes which caused issues when defining the scheme, fixed that too.
Fixes #88

Fix loading webhook endpoints from API and forwarding

---

README.md

Whoops. I realized we forgot to add log tailing to the table of contents in the README. This fixes that.

Add log tailing to table of contents

---

.goreleaser.yml
Dockerfile

Create and publish Docker images for the CLI. This is useful for e.g. k8s or CI/CD deployments.
I've tested the creation part locally with `goreleaser --snapshot --skip-publish --rm-dist` and verified that the images work:
```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
stripe/stripe-cli   latest              6d33eb5410b1        33 minutes ago      15.7MB
stripe/stripe-cli   v0.4.0              6d33eb5410b1        33 minutes ago      15.7MB
alpine              latest              b7b28af77ffe        4 weeks ago         5.58MB
$ docker run --rm -it stripe/stripe-cli --version
stripe version v0.4.0-next (beta)
```
I'm less sure about the publishing part, I think we'll have to create a new …

Create and publish Docker images

---

pkg/cmd/root.go
pkg/cmd/samples.go
pkg/samples/list.go
pkg/samples/os.go
pkg/samples/os_test.go
pkg/samples/samples.go
pkg/samples/samples_test.go

r? @aarongreen-stripe @ob-stripe 
cc @stripe/dev-platform @adreyfus-stripe @ctrudeau-stripe 
Renames everything to samples

Rename all mentions of recipes to samples

---

pkg/cmd/delete.go
pkg/cmd/get.go
pkg/cmd/post.go
pkg/cmd/resource/operation.go
pkg/cmd/resource/resource.go
pkg/cmd/resources.go
pkg/requests/base.go

Add support for passing request parameters as arguments instead of having to use the `-d` flag in resource commands.
Unfortunately the current state of the code makes it kind of difficult to write automated tests for this, I think we'd need to do some refactoring of the UI layer as well as the `requests` package (to inject the API key).
I did do some manual testing:
```sh
$ ./stripe charges update --help
Usage:
stripe charges update <charge> [param1=value1] [param2=value2] ...
Flags:
-v, --api-version string      Set the Stripe API version to use for your request
-c, --confirm                 Automatically confirm the command being entered. WARNING: This will result in NOT being prompted for confirmation for certain commands
-e, --expand …
```

Add support for passing request parameters as arguments

---

pkg/cmd/completion.go
pkg/cmd/delete.go
pkg/cmd/get.go
pkg/cmd/listen.go
pkg/cmd/post.go
pkg/cmd/root.go
pkg/cmd/templates.go
pkg/cmd/trigger.go

A bunch of improvements to help messages:
- wrap flag descriptions according to terminal width \o/
- make short messages shorter to ensure that command descriptions fit under 80 characters
- make short messages more consistent (don't use third person, don't add a trailing `.`)
- add required arguments to `delete`/`get`/`post` and `trigger`
- use the dedicated `Example` arg where applicable

Help improvements

---

Dockerfile

Alpine is only provided with a restrained set of useful packages which didn't contains `ca-certificates` that handle certificate checking. Thus preventing stripe-cli to connect to stripe API.
r? @ob-stripe 
This PR adds `ca-certificates` package to alpine to allow stripe-cli to connect to stripe API over __HTTPS__.

Update docker container to allow https connections

---

pkg/cmd/logs/tail.go
pkg/logtailing/tailer.go

r? @tomer-stripe @ob-stripe 
A user [reported](https://github.com/stripe/stripe-cli/issues/102) an issue with the `--format` argument for log tailing.
This converts the supplied argument to uppercase before doing the comparison, and fixes the issue reported by the user.

Fix json format casing specification

---

go.mod
pkg/ansi/ansi.go
pkg/ansi/init_windows.go

r? @brandur-stripe @aarongreen-stripe @tomer-stripe 
The Windows console does not support ANSI color codes, resulting in strange characters in the output (cf. #93). With Windows 10, the console _can_ support ANSI colors, but support must be explicitly enabled.
This PR does that by using some code adapted from this comment: https://github.com/sirupsen/logrus/issues/496#issue-210627761.
It also changes the [spinner charset](https://github.com/briandowns/spinner#available-character-sets) to use standard ASCII characters on Windows, since the default console font does not support the fancy characters.
Fixes #93 (to an extent).

Fix color support for Windows 10

---

pkg/cmd/listen.go
pkg/proxy/proxy.go

r? @aarongreen-stripe @brandur-stripe @tomer-stripe 
Adds a `--skip-verify` flag to the `listen` command that disables certificate verification when forwarding to an HTTPS endpoint.
Fixes #108.
I've tested this manually:
```sh
$ ./stripe listen --forward-to https://localhost:4443
> Ready! Your webhook signing secret is whsec_... (^C to quit)
[Thu, 15 Aug 2019 14:18:28 PDT]  INFO Received event: evt_123 [type: payment_intent.created]
[Thu, 15 Aug 2019 14:18:28 PDT] ERROR Failed to POST event to local endpoint, error = Post https://localhost:4443: x509: certificate is valid for stripe.com, not localhost
$ ./stripe listen --forward-to https://localhost:4443 --skip-verify
> Ready! Your webhook signing secret is whsec_... (^C to quit)
[Thu, 15 Aug 2019 14:18:45 PDT] …
```

Add a flag to skip certificate verification

---

pkg/cmd/resources.go
pkg/cmd/root.go
pkg/cmd/templates.go

r? @ob-stripe 
I wanted to make the resources command call out more prominent, it felt like it was buried a bit. It now looks like:

Make the resources command more prominent

---

pkg/cmd/root.go
pkg/config/config.go
pkg/config/profile.go

r? @ob-stripe @aarongreen-stripe @brandur-stripe 
This lets the CLI read persisted color settings configured by users.
* I set the default color to `""` so that we know if someone is using the command line flag we should override the pre-defined configs
* I moved reading the profile config in to be a bit higher so that we can set the log colors sooner
* `GetColor` reads off the profile (like most other settings) and checks if color is provided first at a top level, then if it's set in the config file. If it's unset in the config file, it returns `""` and goes with auto.

Read from persisted color settings

---

pkg/config/config.go
pkg/config/profile.go

r? @ob-stripe 
Adds some missing comments to color configurations

Add missing comments for exported code

---

go.mod
go.sum
pkg/ansi/ansi.go
pkg/ansi/markdownterm.go
pkg/ansi/markdownterm_test.go

Add a terminal renderer for Markdown strings, that can optionally use ANSI sequences.
The renderer is very basic and only supports a small subset of Markdown features, but it should be enough for rendering the documentation strings from the OpenAPI spec.
Markdown parsing is done by the [Blackfriday](https://github.com/russross/blackfriday) library.

Add a terminal renderer for Markdown strings

---

README.md

r? @tomer-stripe @ob-stripe
Adds the `--forward-connect-to` listener flag to the README.

Update README.md to mention --forward-connect-to flag

---

pkg/cmd/open.go

r? @ob-stripe 
cc @stripe/dev-platform @auchenberg-stripe 
If no args are passed in, print out the supported shortcuts.
fixes #134

Fix a panic crash if running open with no args

---

pkg/cmd/resource/operation_test.go
pkg/cmd/root.go
pkg/config/profile.go

r? @ob-stripe 
Fixes global flags. The old methods need to use `BindPFlags`, but that has a weird side-effect of writing empty fields in the config file. This sets the values inside of the config profile struct directly instead.

Fix global api key and device name flags

---

pkg/cmd/samples/create.go
pkg/samples/os.go
pkg/samples/samples.go

* Double checks that the folder doesn't exist _before_ starting anything
* If someone ctrl+c's in the select prompts, back out properly
* Intercept ctrl+c after the prompt selects and clean up the folder created

Handle ctrl+c properly for samples

---

pkg/samples/samples.go

Request from @romain-stripe to properly capitalize the languages in the select prompt. I hardcode mappings from the folder name to the display name and vice versa to map the selections the user makes.

Capitalize the language names in the selection prompt

---

go.sum
pkg/cmd/resource/operation.go
pkg/login/client_login.go
pkg/login/interactive_login_test.go
pkg/login/poll.go
pkg/requests/base.go
pkg/validators/validate.go
pkg/validators/validate_test.go

A few fixes for live mode support:
- read and persist live keys in the login flow
- remove the live key check
- fix `--livemode` flag in operation commands

Live mode fixes

---

go.mod
go.sum
pkg/cmd/samples.go
pkg/cmd/samples/fixtures.go
pkg/samples/fixtures.go
pkg/samples/fixtures_test.go

cc @stripe/dev-platform @adreyfus-stripe @ctrudeau-stripe 
_I copied this PR over from #125 since that PR got a bit weird with a bunch of rebasing on the parent_
This implements a relatively simple `fixtures` command that takes a json file of a specific structure and makes requests to the API. The JSON files looks like:
```
{
"_meta": {
"template_version": "0"
},
"fixtures": [
{
"name": "cust_bender",
"path": "/v1/customers",
"method": "post",
"params": {
"name": "Bender Bending Rodriguez",
"email": "bender@planex.com",
"address": {
"line1": "1 Planet Express St",
"city": "New New York"
}
}
},
{
"name": "char_bender",
"path": "/v1/charges",
"method": "post",
"params": {
"customer": "${cust_bender:id}",
"source": "tok_visa",
"amount": "100",
"currency": …
```

Implement fixtures functionality

---

pkg/cmd/root.go

I noticed the `login` command appeared twice in `help`, turns out we defined it twice. I removed that but also sorted to avoid that happening again.

Sort cmds and remove duplicate login

---

pkg/cmd/listen.go
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go

Event filtering only filters events when POSTing requests, but it should also prevent them from being displayed at all. This PR handles that case by setting up a map to check against when processing the webhook event

Do not display or print filtered events

---

.golangci.yml

New linter version automatically enabled function length linters, disable those

Disable function length

---

pkg/cmd/root.go
pkg/cmd/templates.go
pkg/cmd/templates_test.go

We don't need to render the login text all the time so hide this if there's a config file. We also have existing behavior that'll raise an error for users if they try to run a command that requires an API key but one isn't set.

Hide login text if there's a config file

---

pkg/config/config.go

r? @ob-stripe 
`stripe config -e` broke if the EDITOR environment variable was empty on mac/linux, now defaults to vi (which we assume to be installed).

default to vi on mac/linux for `config -e` if no EDITOR set

---

pkg/cmd/root.go

Adds `-p` shorthand for `--project-name`

Add short hand for project-name

---

pkg/validators/validate.go
pkg/validators/validate_test.go

Return a better error if an api key is not configured

Return a better error if an api key is not configured

---

README.md
pkg/cmd/listen.go

r? @ob-stripe 
Small change, we were using `localhost:3000` and `localhost:9000` inconsistently. I've settled on the former.

Make sure we're using the same localhost url consistently

---

pkg/useragent/useragent.go
pkg/useragent/useragent_test.go

r? @ob-stripe 
Our CLI was being flagged by AVG anti-malware tool, it was suspected this was because we were shelling out to `uname` to retrieve info. 
In my experience determining why a particular AV would choose to flag a golang binary is opaque, still though using the uname syscall is preferable here over shelling out.

#43: use uname syscall instead of shelling out

---

pkg/cmd/config.go

r? @ob-stripe 
`stripe config` used to handle things with a confusing mix of boolean flags and unflagged args; now:
- `--unset field` is handled as a string flag vs a single arg + bool flag combination
- `--set field value` works vs just having fields set by unexplained args
- `stripe config` with no flags or unexpected flags/args defaults to showing the help page

small fixes to `stripe config` flags

---

pkg/cmd/templates.go

Hide the `get`, `post`, and `delete` commands in favor of people using the resource commands. We don't want to delete them so that people could still use them so we're opting to remove them from the main documentation.

Hide the get, post, and delete commands

---

pkg/useragent/uname_unix.go
pkg/useragent/uname_unix_test.go

r? @ob-stripe 
A previous fix to use uname syscall over shelling out to uname on Unixes introduces some null bytes into the user agent string, these are now removed.
See DX-4729 for more info
Fixes #182.

fix trailing null bytes issue in uname

---

pkg/login/client_login.go

This checks if the CLI is possibly running in an SSH client and if it is, prints the url instead of trying to open the browser (pulled from here: https://unix.stackexchange.com/questions/9605/how-can-i-detect-if-the-shell-is-controlled-from-ssh)
I tried to see if there was a good test to add here but since we're not catching stdout I wasn't sure of a decent way to validate this. Open to ideas!

Check for ssh clients when logging in

---

pkg/cmd/trigger.go

r? @ob-stripe 
for https://jira.corp.stripe.com/browse/DX-4702: `stripe trigger` used to succeed/fail quietly, we now print a quick success message for good API requests and the error for requests that fail. original ticket suggested supplying the event ID but this is nontrivial as event IDs aren't returned in API responses.

give user success/failure feedback for `stripe trigger`

---

.pre-commit
Makefile

r? @ob-stripe 
Added a file `.pre-commit` to our repo that can be manually added to your githooks or automatically via `make githooks-init`, so when you run `git commit` our `make lint` will be run to give you feedback more quickly

add pre-commit hook to run linters

---

pkg/ansi/ansi.go
pkg/logtailing/tailer.go
pkg/requests/base.go

Adds a dark color scheme for terminals with lighter background colors:
A bit limited by what ansi colors are supported so it's not perfect, but it's a step up.

Add a dark color scheme for json colorize

---

pkg/cmd/trigger.go
pkg/requests/examples.go
pkg/requests/examples_test.go
pkg/validators/cmds.go

r? @ob-stripe
The CLI should be able to replay the exact webhook being sent to a user within a few minutes of receiving it.
e.g.
```
stripe trigger --event evt_123
```
DX-3594

Add feature to resend webhook based on event-id

---

pkg/cmd/listen.go
pkg/cmd/listen_test.go
pkg/proxy/endpoint.go
pkg/proxy/endpoint_test.go
pkg/proxy/proxy.go

r? @joek-stripe @joek
cc @stripe/dev-platform @ob-stripe @ob
Allows users to add custom headers when running CLI "listen" command. Strips whitespace and sanitizes sub 0x20 ascii characters.
Fixes #129.

Forward custom headers

---

pkg/cmd/root.go

r? @ob-stripe @brandur-stripe @romain-stripe @mg-stripe 

Change intro wording

---

pkg/cmd/samples/create.go
pkg/cmd/samples/fixtures.go

Fixtures was crashing when no arguments were given because it requires a file name. Adding a validator to prevent invoking the command without one.

Add a validator for fixtures commands

---

.golangci.yml
pkg/cmd/listen.go
pkg/login/interactive_login.go
pkg/login/login_message.go
pkg/login/poll.go
pkg/proxy/endpoint.go
pkg/proxy/endpoint_test.go
pkg/proxy/proxy.go
pkg/websocket/messages_test.go
pkg/websocket/request_log_messages_test.go
pkg/websocket/webhook_messages.go
pkg/websocket/webhook_messages_test.go

cc @stripe/dev-platform @ballantyne-stripe @carolinem-stripe 
Include the forward URL in webhook responses, so we can use it to display it in the dashboard.

Send forward URL in webhook responses

---

pkg/cmd/samples/create.go
pkg/cmd/samples/list.go

r? @ob-stripe 
I added some better handling when people try to create a samples that's not currently supported. I also added some explicit sorting to the list command because golang randomizes it each time.

Whitelist supported samples and sort list

---

pkg/cmd/trigger.go
pkg/requests/examples.go
pkg/requests/examples_test.go

r? @ob-stripe 
Added `stripe trigger checkout.session.created` which will exercise the new checkout session flow from the CLI
[dx-4745] closes #151

Add support for creating a Checkout Session via the CLI

---

pkg/cmd/gen_resources_cmds.go
pkg/cmd/resource/operation.go
pkg/cmd/resource/operation_test.go
pkg/cmd/resources_cmds.go
pkg/cmd/resources_cmds.go.tpl

r? @ob-stripe 
on operation commands such as `stripe customer create`, we currently pass in details such as customer shipping address or email as URL-style `email=a@a.com` query args, e.g. `stripe customer create email=a@a.com balance=5`. this changes the operation interface so that string and int parameters are taken as flags, e.g. `stripe customer create --email a@a.com --balance 5`. nonscalar parameters are still taken in the old format but must be under a `-d` flag, e.g. `stripe customer create --balance 5 -d "shipping[name]=name"`. only parameters in the request URL are still accepted as args.

pass simple parameters to operation commands in as flags instead of URL-style query args

---

pkg/logtailing/tailer.go

[wip] 
r? @ob-stripe 
Changes to tailer to allow 'logs tail' to accept error info from request log events, and print to user.

Display error properties when tailing logs

---

pkg/cmd/resource/operation.go
pkg/requests/base.go
pkg/requests/base_test.go
pkg/requests/examples.go
pkg/samples/fixtures.go

When an API request fails during a `trigger` or `fixtures` command, we want to error out immediately rather than proceed normally. This will result in better errors, especially if the API request that fails is not the last one, since in most cases we want to extract something from the API resource, which would fail with a non-obvious error if the "resource" that is returned is actually an error object (cf. https://github.com/stripe/stripe-cli/issues/151#issuecomment-536786023).

Return error on non-2xx status in trigger and fixtures

---

pkg/cmd/listen.go
pkg/cmd/logs/tail.go
pkg/cmd/open.go
pkg/cmd/samples.go
pkg/cmd/samples/create.go
pkg/cmd/samples/fixtures.go
pkg/cmd/samples/list.go
pkg/cmd/status.go
pkg/cmd/trigger.go

This adds version checks to a number of CLI commands that would benefit from running on the latest version. Version checking fails silently so this will never prevent running any of the commands.

Add version check to a number of commands

---

go.mod
pkg/cmd/resource/operation.go
pkg/cmd/templates.go

Group request parameters flags separately from "normal" flags in help messages.
Couple of screen shots:

Group request parameters flags separately in help messages

---

README.md
pkg/cmd/delete.go
pkg/cmd/get.go
pkg/cmd/post.go
pkg/cmd/resource/operation.go
pkg/cmd/resource/operation_test.go
pkg/requests/base.go

Use dashes instead of underscores in flag names for request parameters (e.g. `--statement-descriptor` rather than `--statement_descriptor`).
I also had to rename the global `--api-version` flag to `--stripe-version`, because one of the requests does accept an `api_version` parameter, which is now rendered as an `--api-version` flag.

Use dashes instead of underscores in flag names

---

pkg/proxy/endpoint.go
pkg/proxy/endpoint_test.go
pkg/proxy/proxy.go
pkg/websocket/webhook_messages.go
pkg/websocket/webhook_messages_test.go

The stripecli backend service now sends a `webhook_conversation_id` property in addition to `webhook_id` in webhook event messages. This PR updates the CLI to pass this ID back to the stripecli backend service when sending webhook responses, so we can link the webhook CLI response to the webhook conversation.

Pass webhook conversation ID back to backend

---

pkg/config/config.go

r? @brandur-stripe  @tomer-stripe @joek-stripe 
Use 0600 (`rw-------`) instead of the default 0644 (`rw-r--r--`) for the default configuration file. Since it stores API keys (and in the future may store _live_ API keys), it's important to keep it secure.
I used viper's `SetConfigPermissions` method, but that only applies to creating new files, so I also added a manual permissions change to fix existing files.
Not that this only applies to the default configuration file. If the user provides a custom file with `--config`, it's their responsibility to secure the file.

Fix config file permissions to not be world-readable

---

pkg/cmd/trigger.go
pkg/requests/examples.go
pkg/requests/examples_test.go

r? @
Trigger for `payment_intent.canceled` has been added
Issue stripe/stripe-cli#228

Add trigger for 'payment_intent.canceled' event

---

README.md

r? @ob-stripe 
Add port number to `apt-key adv` command. See #231 for context.

Update README for #231

---

Makefile

r? @ob-stripe 
Add a `clean` target to the Makefile to clear out files generated by the build.

Add clean make target

---

pkg/cmd/resource/events.go
pkg/cmd/resource/events_resend.go
pkg/cmd/resource/events_resend_test.go
pkg/cmd/root.go
pkg/cmd/trigger.go
pkg/requests/examples.go
pkg/requests/examples_test.go

cc @stripe/dev-platform @rattrayalex-stripe 
- Removes the `--event` flag in the `trigger` command (`trigger` is now exclusively used to trigger new test events, not replay existing ones)
- Add a new `events resend` subcommand (`events` already has `retrieve` and `list` subcommands which are regular API operation commands). The command expects one argument (the event ID) and accepts two optional flags: `--webhook-endpoint` to replay the event on a specific endpoint and `--account` to replay an event from a connected account. If `--webhook-endpoint` is omitted, then the CLI will send `for_stripecli=true` in the request to instruct the API to replay the event to the CLI endpoints.
Because the new command inherits all the standard API operation command infrastructure, it …

Add events resend command

---

Makefile
pkg/login/client_login.go
pkg/login/login_message.go
pkg/login/poll.go
pkg/logtailing/tailer.go
pkg/proxy/proxy.go
pkg/requests/base.go
pkg/samples/samples.go
pkg/stripe/client.go
pkg/stripe/client_test.go
pkg/stripeauth/client.go
pkg/stripeauth/client_test.go
pkg/websocket/client.go

Improves the synchronization of all goroutines in websocket commands:
- create a cancelable [context](https://blog.golang.org/context)
- start a goroutine who will be blocked until Ctrl+C is pressed. When Ctrl+C is pressed, the goroutine cancels the context
- create a goroutine for the session creation request and pass the context to the HTTP client
- block until the goroutine returns
- if the session creation succeeds, pass the context to the websocket client
- block until either the context is canceled or the client is connected
- at this point only, display the success message (previously we would start the websocket client goroutine and immediately display the success message despite the fact that the websocket client was still connecting) …

Better synchronization for websocket commands

---

pkg/cmd/resources.go
pkg/cmd/resources_test.go
pkg/cmd/templates.go

r? @ob-stripe 
Made a few clean-up changes to the help menu for resources:

Clean up the help menus around resources

---

README.md
pkg/cmd/root.go
pkg/stripe/client.go
pkg/stripe/telemetry.go
pkg/stripe/telemetry_test.go

Add very basic telemetry: send the command path (e.g. `charges create`, `listen`, etc.) in API requests, in a new `Stripe-CLI-Telemetry` header.
The header contains a JSON string, so we can easily add more information in there.
Users can opt out of telemetry by setting `STRIPE_CLI_TELEMETRY_OPTOUT` to `1` or `true`.

Telemetry: command path

---

pkg/cmd/listen.go
pkg/proxy/proxy.go

Allow `--forward-connect-to` to be used when `--forward-to` is not passed. In that case, only Connect events will be forwarded.
Fixes #242.

Allow --forward-connect-to without --forward-to

---

pkg/cmd/resource/events_resend_test.go
pkg/cmd/resource/operation_test.go
pkg/cmd/root_test.go
pkg/login/interactive_login_test.go
pkg/login/login_message_test.go
pkg/logtailing/tailer_test.go
pkg/proxy/endpoint_test.go
pkg/requests/base_test.go
pkg/requests/examples_test.go
pkg/samples/fixtures_test.go
pkg/samples/samples_test.go
pkg/validators/validate_test.go
pkg/websocket/client_test.go

I don't think this changes much in practice, but it makes the test's intent clearer.

Use `require.NoError` where applicable

---

pkg/cmd/gen_resources_cmds.go
pkg/cmd/resources_cmds.go
pkg/requests/base.go

Define flags for request parameters in GET and DELETE requests. (In practice, mostly list requests, since the majority of retrieve and delete do not have any parameters.)

Add flags for GET request parameters

---

pkg/cmd/root.go
pkg/config/profile.go

We're thinking that viper's automatic env wasn't playing well with how we setup user profiles. Since the two most likely cases of env variables are `device_name` and `api_key` this adds a quick check for those and uses that if found.

Manually check for env variables and disable the automatic ones

---

pkg/cmd/gen_resources_cmds.go
pkg/cmd/resources_cmds.go
pkg/cmd/resources_cmds.go.tpl
pkg/spec/spec.go

Do not generate commands for deprecated API methods.
I'm not thrilled with the implementation (the template file has too much logic) but this works for now. At some point I want to change the entire generation process to simply transform the OpenAPI spec file into a giant Go structure and simply use the struct at runtime for our needs, instead of directly generating the final Go code. This would be slightly less efficient but the vast majority of the time spent processing the OpenAPI is just parsing the JSON file into memory anyway.

Do not generate commands for deprecated API methods

---

.goreleaser.yml

Create `.zip` archive instead of `.tar.gz` for Windows binary.
Tested locally:
```
$ goreleaser --snapshot --skip-publish --rm-dist
$ ls dist/stripe_v0.8.2-next_*
dist/stripe_v0.8.2-next_linux_amd64.deb      dist/stripe_v0.8.2-next_mac-os_x86_64.tar.gz
dist/stripe_v0.8.2-next_linux_amd64.rpm      dist/stripe_v0.8.2-next_windows_x86_64.zip
dist/stripe_v0.8.2-next_linux_x86_64.tar.gz
```
Fixes #260.

Create .zip archive instead of .tar.gz for Windows binary

---

pkg/cmd/completion.go

cc @stripe/dev-platform @auchenberg-stripe 
Try to automatically detect the shell for the user when generating completion scripts
Fixes #269

Try to automatically detect shell

---

.goreleaser.yml

Add explicit `--shell` flag to `completion` command in the brew install script.
Fixes #279.

Add explicit --shell flag to completion comand in brew formula

---

pkg/stripe/telemetry.go

This is a small patch to simplify the logic for the `telemetryOptedOut` function.

Simplify boolean logic

---

pkg/cmd/resources_cmds.go
pkg/gen/gen_resources_cmds.go
pkg/requests/base.go

Generate flags for some scalar types that were previously omitted (`boolean` and `number`).

Generate flags for more scalar types in resource commands

---

Makefile

With a fresh clone, `lint` would fail because nothing calls `setup` as prerequisite.
This slims down `setup` in favor of an approach with more granular Makefile dependencies.

Have `make lint` work out-of-the-box

---

pkg/cmd/root.go
pkg/stripe/telemetry.go

r? @ob-stripe 
* Adds device name to telemetry
* Tags whether the command was a generated resource

Add device name and generated flag

---

pkg/cmd/samples/create.go
pkg/git/git.go
pkg/samples/samples.go

cc @stripe/dev-platform @adreyfus-stripe @thorsten-stripe 
* Added a boolean flag for `--force-refresh` that'll delete any local cache for a sample
* Fixed the cache update logic, was missing a pull step at the end.

Update the samples cache mechanism to correctly pull diffs/changes

---

pkg/ansi/ansi.go
pkg/proxy/endpoint.go
pkg/proxy/endpoint_test.go
pkg/proxy/proxy.go

cc @stripe/dev-platform @cjavilla-stripe 
Do not follow redirects when POSTing webhook events to the local endpoint(s). This reproduces the behavior of real webhooks, where any status code >= 300 is considered a failure.
I suspect this was the real issue behind #114.

Don't follow redirects when POSTing webhook events

---

pkg/cmd/fixtures.go
pkg/cmd/resource/operation.go
pkg/cmd/samples/create.go
pkg/cmd/trigger.go
pkg/requests/base.go
pkg/validators/cmds.go

r? @
In regards of #308 , I tried to list the existing commands and make it show help instead of just the error message so that the user can get a clearer idea of what to do.
For the most of it, I only tried to check for the case of when the length of the arguments given are 0 (only `stripe <command>` since that should be the most frequent case of usage. The downside of this is the `err` that is going to be returned is becoming `nil` with the trade-off of showing a clean nice help message instead that should probably give the user a clearer guide.
- For all of the commands, I edited the package `validator` of `ExactArgs` to output `cmd.Help()` and `nil` `err` instead when the length of the arguments are 0.
- For `fixtures` and `create` subcommand of command …

Show consistent help when error appears

---

README.md

r? @
Docker containers cannot use `stripe-cli login` unless you use volumes to store the login data. Instead use the `--api-key` option to authenticate. I guess an additional example would help out to clarify that.

Add example to run Docker container

---

pkg/cmd/listen.go
pkg/cmd/listen_test.go

More faithful forward URL building when using `--load-from-webhooks-api`.
Fixes #322.

Better forward URL building

---

pkg/cmd/resource/operation.go
pkg/validators/cmds.go

r? @ob-stripe 
Realized that #323 introduced a small bug that prevented create commands from working since they don't usually have arguments. I removed that here for now. I also removed the help print from the validation error to be consistent with our other errors that return instead of print.

Fix create commands not working

---

pkg/cmd/fixtures.go
pkg/cmd/trigger.go
pkg/fixtures/fixtures.go
pkg/fixtures/fixtures_test.go
pkg/fixtures/triggers.go
pkg/requests/base.go

Add a `--stripe-account` flag to the `trigger` and `fixtures` commands to execute the fixture on a connected account.
Fixes #293.

Add `--stripe-account` flag to `trigger` and `fixtures`

---

.golangci.yml
Makefile

r? @ob-stripe 
cc @stripe/dev-platform @suz-stripe 
I wanted to disable `gomnd` but I needed to update the golangci version. While doing that I noticed that `enable-all` is deprecated and going to be remove and the preferred pattern is now to use `disable-all` and opt-in: https://github.com/golangci/golangci-lint#config-file
`make lint` passes right now, hopefully I didn't miss anything big.

Update golangci config file

---

pkg/login/poll.go

I caught this with my [linter](https://github.com/gsquire/dll) while reviewing the code for learning purposes. I know retries may not happen frequently but if they did, they were leaking the previous connection's response body.

Remove a defer statement inside of a loop

---

pkg/samples/list.go

cc @adreyfus-stripe 
Adding link to stripe-sample for developer office hours. We're adding a mostly empty Stripe Sample that viewers can install with `stripe samples create developer-office-hours` which will serve as a standard starting point with boilerplate already populated so the user only needs to write the code to grasp the concept covered in the episode.

Add Developer Office Hours Starter Sample

---

pkg/cmd/trigger.go
pkg/fixtures/triggers.go

Fixes a bug where the `api-base` flag was ignored when running the `trigger` command.

use api-base flag when running trigger command

---

pkg/proxy/proxy.go
pkg/stripeauth/client.go
pkg/stripeauth/messages.go
pkg/websocket/client.go

This reverts commit b0c4eec195ca4e8de04aff21426cf6e19754e4a2.
r? @ob-stripe @mcavage-stripe 
Explained in the issue in #401 -- reverting so we can find a solution that will always be in sync with the webhook endpoint.

Revert "#401 Display API Version when running listen (#404)"

---

pkg/websocket/client.go

r? @ob-stripe 
* Changed the read error to debug-level instead of error, from testing it looks like this isn't causing the CLI to stop working
* Adding a default case to catch other possible errors that are coming up

Add additional debuging

---

pkg/cmd/config.go
pkg/cmd/delete.go
pkg/cmd/open.go
pkg/cmd/post.go

r? @tomer-stripe
**Primary change:** Add new listing for cliref in shortcuts used for `open` command.
**Secondary changes:**
- Remove lines which state `post` and `delete` can only be used in testmode.
- Fix small typo `let's -> lets`

Add shortcut for cliref in open command

---

pkg/fixtures/fixtures.go
pkg/fixtures/fixtures_test.go

r? @thorsten-stripe @tomer-stripe 
The root issue of env variables not working in the fixture `path` was that the
`parsePath` method was not using the same regex pattern that was used in
`parseParam`. This divergence caused the env variables to be supported as
params but not in a path.
After adding a test and creating a common util function to extract the
fixture query matches it was found that even the regex pattern that
seemed to work for both cases needed to be tweaked for the case where
multiple fixture queries are used in a row as with:
```
/v1/charges/${char_bender:id}/capture/${cust_bender:id}
```
The screenshots below show the matching issues with the previous patterns and the new pattern matching.

Add fix around regex pattern used for matching fixture queries

---

.goreleaser.yml
.travis.yml

This PR enables the use of cgo for all binaries, which should fix the DNS issue on macOS that some users have been observing, caused by a known upstream issue in Go itself (https://github.com/golang/go/issues/12524).
Instead of running GoReleaser directly in Travis, it's now run in a Docker image that is set up specifically to be able to use cgo when compiling binaries for macOS and Windows: https://github.com/mailchain/goreleaser-xcgo.
The Docker image is fairly simple: it's based on the official `dockercore/golang-cross` image, and simply adds GoReleaser and Docker to the container (we need Docker inside the Docker container itself, because GoReleaser needs to be able to push the Docker image it creates to the central …

Use mailchain/goreleaser-xcgo Docker image

---

.goreleaser.yml
Dockerfile

Fix Docker image.
My change from yesterday to enable cgo (#439) unfortunately broke the Docker image for the CLI, because the Alpine image does not have the required libraries that the cgo-enabled `stripe` binary expects.
I've fixed this by disabling cgo for Linux, and keeping it enabled for macOS and Windows, and verified that the Docker image works again (by building locally). The main reason we wanted cgo was to fix the DNS issue on macOS anyway.
If it turns out that using cgo for Linux is desirable for some reason, there are a few ways we can enable it:
- compile 2 different Linux binaries, one with cgo enabled and one with cgo disabled. Use the first one for distributing and the second one for the Docker image. (This will …

Fix Docker image

---

pkg/cmd/serve.go

Updating the output of `stripe serve` to make it clear it's providing a static file server.

Refine wording for `stripe serve`.

---

pkg/cmd/resource/terminal.go
pkg/cmd/resource/terminal_quickstart.go
pkg/cmd/root.go
pkg/config/profile.go
pkg/terminal/p400/diagnostics.go
pkg/terminal/p400/rabbit_service.go
pkg/terminal/p400/rabbit_service_test.go
pkg/terminal/p400/reader_constants.go
pkg/terminal/p400/reader_errors.go
pkg/terminal/p400/reader_methods.go
pkg/terminal/p400/reader_methods_test.go
pkg/terminal/p400/reader_payment.go
pkg/terminal/p400/reader_registration.go
pkg/terminal/p400/stripe_requests.go
pkg/terminal/p400/user_prompts.go
pkg/terminal/quickstart_p400.go
pkg/terminal/reader_list.go
pkg/terminal/user_prompts.go
pkg/validators/validate.go

r? @tomer-stripe @ob-stripe 
I built a “quickstart” experience for Stripe Terminal into the Stripe CLI, to allow developers to run a test payment on their new Verifone P400 Terminal reader in < 5 minutes.
The command to run (in test mode only) is `stripe terminal quickstart --api-key sk_test_123`
To see a GIF of what the flow generally looks like when using the command, expand the section below:
<details>
<summary>Expand for GIF</summary>
</details>
**Feedback**
All feedback is very welcome!
Would love nitpicky feedback about idiomatic Golang stuff because I'm so new to the language, especially around code duplication and type choices. I made some escape hatches in a few utility functions with interface types but would love guidance around this if you think it's …

add terminal quickstart feature (beta)

---

pkg/cmd/resources_cmds.go
pkg/gen/gen_resources_cmds.go

Generate flags for polymorphic scalar types in resource commands, i.e. polymorphic types where at least one of the types is scalar.
For instance, the `product` parameter in plan creation requests can be a hash or a string. This PR will let users use the string form with `stripe plans create --product=prod_123`, rather than being forced to use the `-d` escape hatch `stripe plans create -d product=prod_123`.
Fixes #352.

Generate flags for polymorphic scalar types

---

.travis.yml

This adds up to 3 retries when running `make ci`, as a stopgap to deal with flaky tests.

Add retry to CI build

---

pkg/websocket/client_test.go

cc @ianjabour-stripe (paired with me)
This test has been causing us much pain. Apparently the websocket client eventhandler can trigger multiple events. This changes the test to block only until the first event comes through and then just go with that, instead of assuming that only one event will ever happen.

Fix Racy Test

---

.github/workflows/test.yml
Makefile
pkg/cmd/root_test.go
pkg/login/client_login_test.go
pkg/login/poll_test.go

+ Added a GitHub Action Workflow to run tests on Linux, Windows, and MacOS.
+ Fixed some issues in tests that failed within a Windows environment
+ Cleaned up Makefile to remove redundant separate install of `misspell` as it was failing to install on Windows. Looking at the `golinter-ci` config it appears that misspell is already installed and runs in this task with the other linters. Is this right?

Add GitHub Action workflow for tests

---

.goreleaser.yml

Add 32-bit Windows build.
I've verified this works with:
```
$ docker run --privileged -v $PWD:/Users/ob/go/src/github.com/stripe/stripe-cli -v /var/run/docker.sock:/var/run/docker.sock -w /Users/ob/go/src/github.com/stripe/stripe-cli -it mailchain/goreleaser-xcgo --snapshot --skip-publish --rm-dist
```
This produces a `stripe_v1.4.1-next_windows_i386.zip` which includes a `stripe.exe` file:
```
$ file stripe.exe
stripe.exe: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
```
(By contrast, the 64-bit version outputs this:
```
$ file stripe.exe
stripe.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```
)
I don't have a 32-bit Windows VM to actually test the .exe, but there's no …

Add 32-bit Windows build

---

pkg/cmd/root_test.go
pkg/validators/cmds.go
pkg/validators/cmds_test.go

Fixes #372 
**Before:**
```shell
$ stripe logs tail foo
tail does not take any arguments. See `stripe tail --help` for supported flags and usage
```
**After:**
```shell
$ go run cmd/stripe/main.go logs tail foo
`stripe logs tail` does not take any positional arguments. See `stripe logs tail --help` for supported flags and usage
```
**Before:**
```shell
$ stripe samples create foo foo foo
create only takes 2 arguments (or less). See `stripe create --help` for supported flags and usage
```
**After:**
```shell
$ stripe samples create foo foo foo
`stripe samples create` accepts at maximum 2 positional arguments. See `stripe samples create --help` for supported flags and usage
```
**Before:**
```shell
$ stripe customers delete
delete only takes 1 argument. See `stripe delete …
```

More helpful usage errors

---

pkg/cmd/completion.go

Paired with @ianjabour-stripe on this. Addresses https://github.com/stripe/stripe-cli/issues/446
cc @auchenberg-stripe @ianjabour-stripe 
Causes `stripe completion` to print instructions on how to install bash completion, after successfully generating the completion file.
The instructions are based off of instructions in the [new cli autocompletion docs](https://stripe.com/docs/stripe-cli/configure#autocompletion).
Side Note:
For Bash, we link to https://sourabhbajaj.com/mac-setup/BashCompletion/ from the CLI ref -- those instructions say to add
`[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion` but this didn't work for me -- instead, I had to do as brew instructed `[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . …

Add installation instructions to `stripe completion`

---

pkg/ansi/ansi.go
pkg/cmd/listen.go
pkg/cmd/logs/tail.go
pkg/cmd/samples/create.go
pkg/cmd/status.go
pkg/login/client_login.go
pkg/logtailing/tailer.go
pkg/proxy/proxy.go
pkg/samples/list.go
pkg/terminal/p400/reader_payment.go
pkg/terminal/p400/reader_registration.go
pkg/version/version.go
pkg/websocket/client.go
pkg/websocket/client_test.go

r? @ob-stripe 
cc @tomer-stripe 
- `stripe listen` and `stripe logs tail` now detect when a CLI session is expired, and attempt to create a new one and open a websocket connection with it up to three times, this should fix
https://github.com/stripe/stripe-cli/issues/80
- Change use of `context.Context` to be more idiomatic. From [the docs](https://golang.org/pkg/context/)
> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx:
- Factored `withSIGTERMCancel` out of `proxy.Run` and `tailer.Run`. 
- Hardcoded devbox stripecli to return the expired error, verified the command terminates after 3 attempts. Verified that the command can successfully reconnect when I …

Refresh expired websocket sessions

---

pkg/cmd/listen.go
pkg/proxy/proxy.go

r? @bwang-stripe 
In response to #472, this adds the `--print-secret` flag proposed in #475 to the listen subcommand. This flag will cause `stripe listen --print-secret` to print the webhook signing secret and exit immediately. This can be used in scripts to more easily access the secret instead of parsing the output of `stripe listen.

Add `--print-secret` flag to listen subcommand

---

pkg/cmd/listen.go

Skip the check for latest version in `stripe listen` if `--print-secret` is passed. Issue reported at https://github.com/stripe/stripe-cli/pull/478#issuecomment-658415125.

Don't check for latest version in `listen` if --print-secret is passed

---

pkg/ansi/ansi.go

This change disables animated spinners for non-terminal Writers even when colors are forced with `--color=on`. Relevant use-case in #370.

Don't use animated spinner for non-terminal Writers

---

.goreleaser.yml

We're using [`goreleaser-xcgo`](https://github.com/mailchain/goreleaser-xcgo) to run goreleaser in docker on Travis (due to previous issues. That docker image is running version [`0.127.0`](https://github.com/mailchain/goreleaser-xcgo/blob/master/Dockerfile#L5), which doesn't include the new syntax that I updated to in #502. I don't want to try to update the version on the docker image so I'm undoing this one syntax change for now.

Undo goreleaser config change for homebrew

---

.gitignore
pkg/cmd/playback.go
pkg/playback/http_playback.go
pkg/playback/http_playback_test.go
pkg/playback/interactions.go

cc @stripe/developer-products @tomer-stripe 
`stripe playback` needs to use `stripe listen` while in record mode so it can intercept webhook events from the stripe API and record them.
fixes DX-6101

Run listen command when starting stripe playback

---

pkg/cmd/playback.go

Add --no-listen flag to prevent listen command to be ran by playback
solves DX-6102

Add --no-listen flag to prevent listen command to be ran by playback

---

.github/workflows/test.yml

In go 1.15 (the actual dependency we build against), the URL package was updated with a new default field: https://golang.org/pkg/net/url/#URL
This breaks tests built between 1.14 vs 1.15 on another PR, so I'm actually putting everything on 1.15.

update github actions to go 1.15.x

---

pkg/cmd/listen.go

r? @richardm-stripe @tomer-stripe 
This pull request is a potential solution to PR #496 
This PR adds the `--skip-update` / `-s` flag to allow the user to skip checking for update. This will help improve the speed by avoiding the overhead of checking for new updates.
Example commands for usage of this flag:
- `stripe listen --skip-update`
- `stripe listen -s`

Disable update checking in stripe listen command

---

pkg/playback/http_playback.go
pkg/playback/http_playback_test.go
pkg/playback/http_recorder.go
pkg/playback/http_replayer.go
pkg/playback/http_serializer.go
pkg/playback/http_serializer_test.go
pkg/playback/interactions.go
pkg/playback/interactions_test.go
pkg/playback/yaml_serializer.go
pkg/playback/yaml_serializer_test.go

cc @stripe/developer-products @tjfontaine-stripe @tomer-stripe 
This creates a new `yaml_serializer` system to properly serialize cassettes to yaml and back.
It refactors `interactionRecorder` and `interactionReplayer` to take a `serializer` (in our case the yaml serializer` instead of a `serialize` and `deserialize` methods.
Seems like everything is still working, added some tests, all tests (not enough) pass and below are the logs from playback while I manually tested 
- creating a new customer, getting the req/resp stored
- catching the `customer.create` webhook event and getting it stored
- replaying both the create request and the webhook
> Note: Now that I've done that, I feel like json might be a better serialization since requests/responses are done in json. …

Refactor the serialization system to correctly save human-readable yaml to file

---

pkg/logtailing/tailer.go
pkg/proxy/proxy.go

r? @suz-stripe @richardm-stripe
Fixes #539 
Commit a023543c63cd2719ae3d980ca2173934653773fc introduced `Log.Fatalf` when `ctx.Done()` happens, which logs a FATAL line to the user terminal when they press CTRL+C.
It is not necessary to log FATAL here since closing the process is the intended purpose by the user when pressing CTRL+C

return nil instead of log.Fatal when ctx is closed during Listen and Tailer Run

---

pkg/cmd/playback.go

r? @suz-stripe @richardm-stripe 
Now we are facing conflicts with `WithSIGTERMCancel` between the playback and listen commands when playback runs listen in the background.
Just making sure here we correct exist the process without printing any unnecessary errors.
for #540 we'll have to extract the listen logic outside of the command, so we make sure `WithSIGTERMCancel` is setup at the correct level (cobra command) and not setup twice.

os.Exit when ctrlc

---

.goreleaser.yml
pkg/cmd/postinstall.go
pkg/cmd/root.go
pkg/config/profile.go
pkg/validators/validate.go
pkg/validators/validate_test.go
scripts/postinstall.sh

We received some feedback about the post installation experience of the CLI. Once installed, it's quite common to jump right into running commands with it. Most commands require a user to be logged in and authenticated with Stripe first, so in this scenario they would immediately see an error asking them to log in. That's a bit of a bummer experience right after installing, so it was suggested that we add a post install greeting to remind users to log in first before anything else.
This homebrew log example demonstrates the greeting added as a postinstall step (6th line from the bottom):
```
$: brew install stripe
==> Installing stripe from stripe/stripe-cli
==> Downloading https://github.com/stripe/stripe-cli/releases/download/v1.5.5/stripe_ …
```

add post-installation hint to log in

---

.github/workflows/release.yml

I made a mistake and thought that the two triggers were parsed as an `AND` operation, rather than a list of separate triggers. In other words, "only if branch `master` AND there is a new tag". So I have removed the branches clause for now.

Releaser Action: remove branches from trigger list

---

pkg/cmd/root.go

r? @ctrudeau-stripe 
Turns out that I misunderstood the return value logic of `sort.SearchStrings` which returns a valid slice index _even if the string you're searching for is not present in the slice_ 🤦  
I have removed the usage entirely and converted to a simple pair of conditionals instead which is less fancy and much easier to read.
This was breaking our login checker if an unknown command is run, or if a command is run with the incorrect arguments.

remove incorrect usage of SearchStrings for login check

---

pkg/login/client_login.go
pkg/open/open.go

When a user runs `stripe login` a browser is needed. Not all environments have one available. This attempts to detect if the environment lacks a browser in linux. If it lacks a browser then show the URL to the user for them to login. 
Built the CLI and copied to a docker container running ubuntu without a browser. URL displayed properly. 
Attempts to fix #499 and RUN_DX-1

Adding ability to show URL when no browser is detected on linux

---

pkg/fixtures/fixtures.go
pkg/fixtures/fixtures_test.go

When we unmarshal fixtures from a file we represent `params` as an empty interface. This means that numeric values are parsed as `float64`.
In our logic which translates the values to request params we used the `%v` for float which is translated to `%g` under the hood. The `%g` format will use:
> %e for large exponents, %f otherwise
For more context reference the [docs](https://golang.org/pkg/fmt/) and the comment that was added.
I was able to reproduce the failure in a test case and verify that it is now resolved.

Fix fixture logic which parsed large numbers into scientific notation

---

scripts/publish-deb-to-bintray.sh
scripts/publish-rpm-to-bintray.sh
scripts/upload-zip-to-virustotal.sh

Our scripts were breaking due to a `sh` env incompatibility with double bracket conditionals on GH Actions. I changed the shebangs to `bash` for the affected scripts in order to fix this.

run scripts in bash for double bracket compat

---

.github/workflows/release.yml

We noticed a weird changelog issue since we switched to GitHub Actions for releasing the CLI. After some research, it appears that [Goreleaser recommends](https://goreleaser.com/ci/actions/) using `fetch-depth: 0` for the code checkout step for the Changelog to be generated properly. I missed this in the documentation when initially putting this workflow together.
Also noted from their [GH Action repo README](https://github.com/goreleaser/goreleaser-action#workflow):
> IMPORTANT: note the fetch-depth: 0 input in Checkout step. It is required for the changelog to work correctly.
This should ensure we get all PRs listed in their respective changelogs going forward.

use fetch depth in checkout step for changelog

---

.goreleaser/mac.yml

r? @suz-stripe @ob-stripe @tjfontaine-stripe 
cc @stripe/developer-products 
I know I know, I promised I wouldn't mess with GitHub Actions over the weekend, _but_ ...while I was on my personal laptop I noticed that running `brew update` pulled the new Stripe CLI tap, but `brew upgrade` didn't actually upgrade the CLI to 1.5.10. Unfortunately, the updates we made changed how the homebrew tap was written and explicitly removed the ability to install on arm: https://github.com/stripe/homebrew-stripe-cli/commit/bff31d18426242b5236271a42f02048cc4b90a86#diff-cefd878d3ffd3c6e0675e962b88aec27ffba0e756c569a9f9f72063fc46bb5fb
The conditional went from `if OS.mac?` to `if OS.mac? && Hardware::CPU.intel?`. I think goreleaser is trying to be smart here but I'm not sure how to _not_ have it try to fork …

Build Stripe CLI for ARM

---

.vscode/extensions.json

`ms-vscode.go` has been deprecated: https://github.com/microsoft/vscode-go. It's been replaced with `golang.go`: https://github.com/golang/vscode-go. This'll stop that popup that keeps saying `ms-vscode.go` is missing in the bottom right.

Update the vscode requirements

---

.github/workflows/release.yml
.goreleaser/mac.yml
scripts/upload-zip-to-virustotal.sh

cc @stripe/developer-products @tjfontaine-stripe 
* Update mac checksums file name
* Add a separate step for uploading to virustotal (https://github.com/tomelm/stripe-cli-temp/actions/runs/647103038)
* Updating to goreleaser 0.159.0 (that's what the temp repo had been using this whole time)

Fix mac checksums file, add virus total step, update goreleaser

---

pkg/playback/server_test.go

Issue #610 reports flakey tests here. The error seems to be that the test is trying to GET to the server before it's ready. Adding a 10ms sleep to ensure server is ready before we move on.
will try running the tests a few times see if it continues to fails (can't repro locally so far)

sleep 10ms to make sure test server is ready

---

pkg/cmd/listen.go
pkg/logtailing/tailer.go
pkg/proxy/proxy.go

The --format flag is a string that currently only takes in JSON as a valid input option, similar to the log tailing command.
It's intended to replace the --print-json for the listen cmd. The difference in behavior between --format JSON and --print-json is that the new flag will stripe out all formatting in the payload. 
While working on the event streaming feature in VSCode, the stream was getting partial json because the json was being pretty-printed. This PR updates the listen cmd to behave the same way as the log tail command. 
With the deprecated flag:
New flag:
No flag:

Add format flag to listen cmd

---

pkg/cmd/trigger.go

r? @tomer-stripe
I executed the following command in my Bash:
```bash
stripe trigger payout.failed
```
The command failed with the output "event payout.failed is not supported."
I was not sure if the message came from the Stripe servers (e.g. no endpoint configured for event) or my own app server. Only after researching that neither is probable, I decided to search the Stripe CLI source. I'd like to save other developers some time.

Unsupported event type: Show more detailed error message

---

pkg/fixtures/triggers/checkout.session.async_payment_failed.json
pkg/fixtures/triggers/checkout.session.async_payment_succeeded.json
pkg/fixtures/triggers/checkout.session.completed.json

Update fixtures to use `/v1/payment_pages/cs_` because `/v1/payment_pages?session_id=cs_` is soon to be deprecated. There are 3 of them.
I ran all 3 triggers manually to verify they still work.

Migrate fixtures off Checkout endpoint that will be deprecated

---

pkg/fixtures/triggers/checkout.session.async_payment_failed.json
pkg/fixtures/triggers/checkout.session.async_payment_succeeded.json
pkg/fixtures/triggers/checkout.session.completed.json

Update the Checkout fixtures to use the session ID for /confirm similar to https://github.com/stripe/stripe-cli/pull/623 and to pass `expected_amount`
I ran all 3 triggers manually to verify they still work.

Update Checkout Sessions fixtures with session ID and expected_amount

---

pkg/config/profile.go
pkg/login/client_login.go

We want to add the accountId as a dimension in our VSCode telemetry. Instead of making a network call to poll for changes in the accountId, I'd like to be able to check the values locally by checking the value listed in the user's cli config. 
Before: 
```
stripe-dev config --list
color = ""
[default]
device_name = "st-gracegoo1"
display_name = "Cheese Foundation"
live_mode_api_key = "rk_live_123"
live_mode_publishable_key = "pk_live_123"
stripe_samples_price_recurring_basic_id = "price_1IVjRkIMIxZxvOV4gAKEAOQc"
stripe_samples_price_recurring_pro_id = "price_1IVjRlIMIxZxvOV4X0SvuKxf"
test_mode_api_key = "sk_test_123
test_mode_publishable_key = "pk_test_123"
```
After:
```
stripe-dev config --list
color = ""
[default]
account_id = …
```

Saving accountId to the user profile

---

Makefile

fixes #643
This removes gocenter as the download source.
`make setup` fails when gocenter is under maintenance: https://status.gocenter.io/. Moreover, gocenter will no longer be available starting May 1.
`make setup` works locally after removing GOPROXY.

Remove GOPROXY https://gocenter.io from makefile

---

pkg/fixtures/fixtures.go
pkg/fixtures/fixtures_test.go

cc @stripe/developer-products 
As seen in https://github.com/stripe/stripe-cli/issues/635 when a fixture file references a fixture name that does not exist a null pointer reference error is hit and the user is faced with a stacktrace that makes the CLI look broken.
This PR adds logic to raise a validation error when an undefined fixture is referenced, optionally providing hints as to what fixture the user might be attempting to use.
**Printing validation error with suggestions based on previously defined fixtures:**
**In the case no suggestions were found:**
This can definitely be improved by referencing the line/column which caused the failure, however, this would require a larger rewrite in that the necessary context does not seem available at this time.

Improve validation of fixture name references

---

pkg/cmd/logs/tail.go

This flag was marked as experimental and due to limited usage has been deprecated. This PR removes the logic for the flag.
**No longer listed in help output:**
**Flag is not recognized by the CLI:**
**Example of logs tail still working:**

Remove deprecated `--live` flag from the logs tail command

---

pkg/cmd/samples/create.go
pkg/cmd/samples/list.go
pkg/samples/create.go
pkg/samples/list.go
pkg/samples/samples.go
pkg/samples/samples_test.go

- Hoisted the spinners, user IO, and error handling up to the cobra command
- This removes IO concerns from the samples package
- Added new fields to the `Samples` struct to make it easier to work with 
- Updated and added a couple tests in the samples package
Verified manually by running stripe samples list and creating a variety of stripe samples with and without --force-refresh, with and without a path.
Motivated by https://github.com/stripe/stripe-cli/pull/646, which will be rebased on this.

Refactor stripe samples commands

---

pkg/cmd/samples/create.go
pkg/samples/create.go

In https://github.com/stripe/stripe-cli/pull/652, I made a mistake in the switch statement. Because I didn't include all the cases, we would hit the default case every time. The default case returns an error so sample creation would fail every time.
This adds those unused cases to the switch statement and also renames them to be more accurate.

Fix samples create always failing

---

pkg/cmd/logs/tail.go
pkg/logtailing/tailer.go
pkg/logtailing/tailer_test.go
pkg/logtailing/visitor.go

r? @pepin-stripe
This decouples user IO and the receiving of logs.
- The `Tailer` is concerned with sending data on a channel. The data is either a log, an error, a warning, or a connection state.
- The cobra command, as a client of the `Tailer`, receives these different data types and processes them using a visitor object.
This pattern enables `Tailer` to be used by any class that wants to do something with logs, for example a gRPC service that wants to stream logs, errors, and connection state to a gRPC client. All the class has to do is read from the channel and provide its own visitor object.
This pattern might also work well for https://github.com/stripe/stripe-cli/pull/574. This is quite boilerplate heavy, so I am open to other solutions as well.

Refactor logs tail command with channel and visitors

---

pkg/terminal/p400/rabbit_service.go
pkg/terminal/p400/reader_constants.go
pkg/terminal/p400/reader_methods.go
pkg/terminal/p400/reader_registration.go
pkg/terminal/p400/stripe_requests.go
pkg/terminal/p400/user_prompts.go

The P400 readers have gone through certificate updates for the [new PQDN format](https://stripe.com/docs/terminal/readers/verifone-p400#reader-has-ip-address-and-can-communicate-with-stripe,-but-not-with-your-point-of-sale-application), which adds a random string to the hostname in order to make them fully unique. This was done because using private IPs alone create much higher chances of collisions. The reader firmware now rejects ingress requests the from old hostname format due to the resulting certificate mismatch.
Quickstart was still using the old hostname format and so the feature was broken. I updated it to extract the `base_url` to use in combination with the private IP. 
I manually tested all three flows:
1. Registering new reader, …

patch quickstart to use new base_url attr for reader hostname

---

pkg/cmd/listen.go

A user opened an issue recently because they were getting an index out of bounds error when trying to use the headers param.
They were using the wrong delimiter for separating the Key and Value of the header, updating the docs to make that more clear for the users.
https://github.com/stripe/stripe-cli/issues/662
Before:
After:

Updating the help docs for the header params in the listen command.

---

pkg/rpcservice/middleware.go
pkg/rpcservice/rpc_service.go

For debugging purposes, write debug logs when gRPC methods are invoked. Move the gRPC config output (in the screenshot, this is the host and port number on the first line) from stderr to stdout. For convenience, stderr will be reserved for logs only.

Add debug logs for gRPC method invocation

---

.github/workflows/release.yml

We can't upload to bintray, which causes the release action to fail: https://github.com/stripe/stripe-cli/runs/2687815767?check_suite_focus=true. This disables the "Upload to Bintray" step.
I can't test this change.

Disable uploading to bintray in release action

---

pkg/cmd/samples/create.go
pkg/samples/samples_test.go

This commit changes references in the samples_test.go from https://github.com/stripe-samples/adding-sales-tax to  https://github.com/stripe-samples/accept-a-payment  as the prior repo will be archived soon.

Change references in a test that refers to a Stripe Sample that will be archived soon

---

pkg/cmd/community.go
pkg/cmd/root.go

Adds a new `community` command which directs users to the Stripe Developer Community Discord server.

Add community command

---

pkg/login/client_login.go

Today, you would have to open the default browser whether you want to or not. This prints the URL so you can copy and paste it somewhere else.
Before:
After:

Show URL when you `stripe login`

---

pkg/websocket/client.go

This change adds a new function that sends a proper close frame during the websocket connection termination. 
The codes are from https://datatracker.ietf.org/doc/html/rfc6455#section-7.4. 
I added a log on the server that outputs the code and reason received on the server side. If you have other suggestions for testing let me know and I will run through those as well. 
Without this change we seem to have been getting a code anyway: 
```
DX_RUN-377: beginning close: reason="" code=1000
DX_RUN-220: beginning finalize_close of websocket: merchant_token=acct_28DT589O8KAxCGbLmxyZ websocket_id="cliws_{22078}_OKpaGryJBTOluaZzRd83q2euKIxYzJWJRTFksySl9zClrJbxuz" websocket_state=2
REDIS-EVENT-LOOP: Going to exit since we have no active conns: …
```

Send close frame when terminating websocket connection

---

pkg/fixtures/fixtures.go
pkg/fixtures/fixtures_test.go

r? @ianjabour-stripe @suz-stripe 
A user reported a bug where variables with a query embedded were losing all information outside of that query.
For example, a webhook create fixture with the url param set to `"${.env:BASE_API_URL}/hook/stripe"` was being saved with just the base API because we only keep the result of the query. 
I moved the .env query logic out and added a string replace to add the value back into the original query string. I only did this for the .env variables because I figured this didn't make as much sense for the resourceIds from responses but let me know if we think this will be useful for all query values, because I can also attempt to just move this logic outside of `parseQuery`
https://github.com/stripe/stripe-cli/issues/718
Added a …

[718] Prevent truncation of env var queries

---

pkg/proxy/proxy.go

r? @
The message said it but it was not true and would lead to confusing errors such as below when `--forward-to` was provided but `--forward-connect-to` was not.
```sh
[ERROR] Failed to POST: Post "http:///stripe/payment-webhook": http: no Host in request URL
```

Use `--forward-to` as default value of `--forward-connect-to` as documented

---

pkg/logtailing/tailer.go
pkg/proxy/proxy.go
pkg/samples/samples.go
pkg/stripeauth/client.go
pkg/stripeauth/client_test.go

Updated the Stripe Auth client to optionally send the forward and connect forward URLs to the CLI API service when connecting via `stripe listen`.
I wrote a test to verify the query params get properly included in the request and manually verified in production as well:

Send forward-to URLs when connecting via `stripe listen`

---

pkg/cmd/root.go

issue: https://github.com/stripe/stripe-cli/issues/349
```
st-etsai1:stripe-cli etsai$ stripe-dev
The official command-line tool to interact with Stripe.
Usage:
stripe [command]
Webhook commands:
listen                        Listen for webhook events
trigger                       Trigger test webhook events
Stripe commands:
logs                          Interact with Stripe API request logs
status                        Check the status of the Stripe API
Resource commands:
get                           Quickly retrieve resources from Stripe
charges                       Make requests (capture, create, list, etc) on charges
customers                     Make requests (create, delete, list, etc) on customers
payment_intents …
```

Display error message if flags were given without commands

---

pkg/cmd/root.go

previous PR https://github.com/stripe/stripe-cli/pull/745 checks if a flag was given without command, and shows an error message when it happens. this breaks the other flags like `--version` flag experience when it does not require any command
the original issue was that the `--color` flag was confusing and it was not apparent to users that it needed a command
we will only prompt the user to include a command when `--color` flag was given
cobra also did not output any error message when user enter `stripe --color`
other scenarios where a flag was incorrectly entered would be caught by cobra

bug fix for --color warning message

---

cmd/stripe/main.go
pkg/cmd/daemon.go
pkg/cmd/root.go
pkg/rpcservice/middleware.go
pkg/rpcservice/middleware_test.go
pkg/rpcservice/rpc_service.go
pkg/rpcservice/rpc_service_test.go
pkg/stripe/analytics_telemetry.go
pkg/stripe/analytics_telemetry_test.go

This change adds additional logic in the middleware interceptors to add the `telemetryClient` and `eventMetadata` to the context passed into the RPC functions. This allows us to get telemetry events for each separate RPC call instead of sharing one metadata for the whole of the daemon process. 
An instance of an `eventMetadata` is created on each method call to gRPC.
We use the same instance of `telemetryClient` for the duration the RPC service is up. The instance of the `telemeryClient` is passed to the RPC service when it is created by the daemon command. 
An example of data sent to the analytics service through manual testing
```
p_invocation_id=1beaa848-7919-407d-81e5-96aeb9d6c24c p_user_agent="Stripe/v1 stripe-cli/master" p_os=darwin …
```

Adding telemetry to gPRC calls

---

.github/workflows/release.yml

https://github.com/goreleaser/goreleaser/pull/2572
this PR forces downloading an universal go releaser but universal binaries dont exist for version < 0.182
since CLI is using verion 0.179, this caused the build release to fail
https://github.com/stripe/stripe-cli/runs/4073154456?check_suite_focus=true
because we couldnt find the universal binary in the assets list for v0.179
use an older version of go releaser action instead
https://github.com/goreleaser/goreleaser-action/releases

downgrade go releaser action to avoid downloading universal darwin go releaser

---

go.mod
go.sum

Downgrade the spinner library to fix a rendering bug. See https://github.com/briandowns/spinner/issues/123.
Before: "Getting ready" isn't erased
After: "Getting ready" is erased

Fix rendering bug where the spinner doesn't erase its loading message

---

.vscode/launch.json
pkg/stripe/analytics_telemetry.go
pkg/stripe/analytics_telemetry_test.go

The "Generated Resource" column in the stripe CLI telemetry table has always been false (in both the old and new tables). Historically, this column was created to indicate commands that were generated from the openAPI spec when we run `make update-openapi-sec`. The logic to determine this checks on the Annotations field of the command for the "operations" tag. However, when commands are created Annotations are added to the parent, not the cmd itself. 
This change updates the logic to check the parent cmd's annotation. 
I also added a couple more launch targets for debugging purposes.

Fixing how we infer generated resource for telemetry

---

.github/workflows/release.yml

cc @tomer-stripe @gracegoo-stripe 
Update the GoReleaser version from the github action so we don't get the `bottle :unneeded` warning anymore.
Fixes #768

update goreleaser version in github action

---

pkg/cmd/root.go
pkg/requests/base.go
pkg/requests/base_test.go

cc @remi-stripe 
The restricted API keys created by the CLI expire after 90 days, but any restricted API key can also be forcibly expired by rolling. Previously, when invoking the CLI with an expired key we would render the entire error response body (and also returned a successful exit code):
```
$ stripe accounts retrieve
{
"error": {
"code": "api_key_expired",
"doc_url": "https://stripe.com/docs/error-codes/api-key-expired",
"message": "Expired API Key provided: rk_test_*********************************************************************************************aaaaaa",
"type": "invalid_request_error"
}
}
$ echo $?
0
```
This updates the CLI to handle the `api_key_expired` error and show a tailored error message:
```
$ stripe accounts retrieve
The API key …
```

Show friendly message when API key is expired

---

pkg/websocket/client.go
pkg/websocket/client_test.go

When the timer triggers to reset the connection, a deadlock can occur if the ping write fails during that period.

fix: deadlock when resetting connection

---

pkg/fixtures/triggers.go
pkg/fixtures/triggers/payment_intent.partially_funded.json
pkg/fixtures/triggers/payment_intent.requires_action.json

Adds fixtures to trigger partially_funded and requires_action. This will allow testing of bank transfer payment methods.
Let me know if there's any hygiene changes I should add - I didn't run any codegen or pull the latest API spec etc.

Add fixtures to trigger new BT payment intent events

---

pkg/proxy/proxy.go
pkg/proxy/proxy_test.go

Fix a bug where running `stripe listen` with `--forward-connect-to` would not forward events.
Using `--forward-to <url>` only:
✅ direct events are forwarded to `<url>`
✅ connect events are forwarded to `<url>`
Using both `--forward-to <url 1>` and `--forward-connect-to <url 2>`:
✅ direct events are forwarded to `<url 1>`
✅ connect events are forwarded to `<url 2>`
Using `--forward-connect-to <url>` only:
✅ direct events are NOT forwarded to `<url>`
❌ connect events are NOT forwarded to `<url>`
Using `--forward-to <url>` only:
✅ direct events are forwarded to `<url>`
✅ connect events are forwarded to `<url>`
Using both `--forward-to <url 1>` and `--forward-connect-to <url 2>`:
✅ direct events are forwarded to `<url 1>`
✅ connect …

Fix --forward-connect-to not forwarding events

---

pkg/config/config.go
pkg/open/open.go

This replacement package always looks for the executable in an absolute path, and throws an error if the executable is in a relative path. Note that this only affects the behavior of certain commands on Windows; other operating systems are unaffected.
Internally, see [here](https://jira.corp.stripe.com/browse/RUN_DX-772) for more info.

Replace exec package with execabs

---

.github/workflows/test.yml

Pinning the doc generation version to 1.5.1. We can always update this or remove it if we find we need the latest documentation format but it'll be nice to not have to worry about updating unless we want to.

Pinning protoc-gen-doc to 1.5.1

---

pkg/fixtures/triggers.go
pkg/fixtures/triggers/charge.refund.updated.json

Fixes #828 , adding support for the `charge.refund.updated` event.

Add trigger support for charge.refund.updated event

---

pkg/cmd/completion.go

Fixes #829 , adding support for a new flag `--write-to-stdout` which, rather than creating a file with the appropriate completion script, prints it to standard out.

Add support for flag to output completion file to stdout

---

pkg/proxy/proxy.go
pkg/proxy/proxy_test.go

In API versions up to and including 2017-05-25, the event schema included the
request ID that triggered the event as a string in the event object. However,
this ID is only populated for direct Stripe API calls, and is null when the
event was triggered for another reason (e.g., internal Stripe systems, 3DS
verification callbacks, etc.).
This updates `ExtractRequestData` to handle missing request IDs for older API
versions. It also switches from using reflect to a type switch, which requires
less boilerplate.

Support events <= 2017-05-25 without request data

---

pkg/cmd/root.go
pkg/plugins/plugin.go
pkg/plugins/plugin_test.go
pkg/plugins/utilities.go

Fixes the following:
- Plugin run error was logged without a severity filter
- Missed a `master` reference rename to `local.build.dev`
- Plugins should be automatically managed to catch any unexpected exits
- Plugins should have a startup timeout to prevent any hangs (not a reported bug but a "should do")
- Plugin logger instance was logging as too low a severity
- Properly clean up clients before the CLI exits

Early plugin bug fixes 

---

pkg/cmd/plugin_cmds.go
pkg/cmd/plugin_cmds_test.go

r? @bernerd-stripe 
Fixes an issue where flags were not passed all the way into plugins. We skip the flag parsing in the CLI and pass them as args, letting the plugin parse them instead.

do not parse flags separately from args in plugin cmd

---

pkg/cmd/plugin_cmds.go
pkg/cmd/plugin_cmds_test.go
pkg/plugins/plugin.go
pkg/plugins/plugin_test.go
pkg/plugins/utilities.go

r? @gracegoo-stripe @etsai-stripe 
I made an assumption that executables on Windows do not need a file extension in order to run successfully via a golang `exec` child process. This assumption turned out to be incorrect. Adding an urgent temporary patch to fix this with a lighter touch, before deciding on a more permanent solution.
Also modified the plugin cmd template to parse the flags on the cli side but send the raw args to the plugin child, which gets us the best of both worlds wrt flag compatibility.

plugin fixes for windows and root level flags

---

pkg/stripe/client.go
pkg/stripe/verbosetransport.go
pkg/stripe/verbosetransport_test.go

r? @acomley-stripe 
This updates the stripe Client to make the list of headers printed in verbose mode to be configurable. This is not exposed through CLI flags, but is useful for plugins or potential usage of the CLI's stripe client package.
It also applies some light refactoring to use the `http.Transport` interface instead of `*http.Transport`.

stripe.Client supports custom list of printable headers

---

pkg/cmd/plugin_cmds.go

cc @stripe/developer-products @htheodore-stripe 
The CLI has no context on the valid flags available for each plugin, so we want to skip validation for plugin commands while retaining flag validation for main CLI commands that are knowable. After a couple of iterations on solving this problem, this PR is probably the most balanced and stable. It ensures all flags are parsed correctly for main CLI commands / config overrides, and are delegated correctly to plugins, allowing the plugin to validate the flags from there.

ignore unknown flags for plugin commands

---

pkg/cmd/plugin.go
pkg/cmd/plugin/uninstall.go
pkg/cmd/plugin/upgrade.go
pkg/cmd/root.go
pkg/config/config.go
pkg/config/profile.go
pkg/plugins/plugin.go
pkg/plugins/plugin_test.go
pkg/plugins/test_utils.go
pkg/plugins/utilities_test.go

1. Adds an uninstall command for plugins
2. Fixes a bug to do with logging within the config initialization flow
3. Updates some of the plugin test mocking utilities to expand on what details we can assert
4. Moves the `GetInstalledPlugins` method from the user profile to the user config instead

Add plugin uninstall command

---

.github/workflows/release.yml

Replace the GORELEASER_GITHUB_TOKEN with the default one as recommended here: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
I think this will make releases no longer look like they're being made by Tomer.
Not sure how to test this other than making a release, which I will do after this.

Use the default github token in the release action

---

go.mod
pkg/playback/interactions_test.go
pkg/playback/server_test.go
pkg/playback/yaml_serializer.go
pkg/playback/yaml_serializer_test.go

Fix Dependabot alert which says to upgrade gopkg.in/yaml from v2 to v3.
This is a breaking change, however:
- This package is only used by the playback code, which technically isn't publicly usable.
- The only thing that broke after updating was how the YAML output is indented, which doesn't matter. At least this was all that our existing tests caught.

Update gopkg.in/yaml.v2 to v3

---

.goreleaser/mac.yml
.goreleaser/windows.yml

After merging https://github.com/stripe/stripe-cli/pull/881, I released v1.10.0 to test it out, but it failed to publish to homebrew and scoop: https://github.com/stripe/stripe-cli/runs/6680336742?check_suite_focus=true
I can't give more permissions to the new token, but it turns out I can manually override the token for publishing to [homebrew](https://goreleaser.com/customization/homebrew/) and [scoop](https://goreleaser.com/customization/scoop/), so this PR uses the original token for that.
As with the last PR, not sure how to test this other than making another release, so I guess I'll release v1.10.1 next.

Use previous github token to release to homebrew and scoop

---

.github/workflows/release.yml

Context: After merging https://github.com/stripe/stripe-cli/pull/884, I released v.1.10.1 to trigger the release action. The release action failed because it couldn't find the environment variable I was reading: https://github.com/stripe/stripe-cli/runs/6694623367?check_suite_focus=true. This PR will hopefully set the environment variable correctly. As always, not sure how to test other than to make a release, so I'll release v1.10.2 after this.

Pass github token from repo to goreleaser

---

pkg/cmd/root.go

When running command with the `--project-name=...` flag, the CLI would run `stripe login...` like so:
Changes this message so that it instead asks the user to run `stripe login --project-name...`:
The same message should show up when the shorthand flag `-p` is used, and when multiple flags are used in the command:

run stripe login with project name flag if config not found

---

.github/workflows/release.yml
.github/workflows/test.yml

r? @
Update GitHub actions to run against go 1.18 instead of 1.17 (all of our devices are likely running against 1.18.x)

GitHub actions should run+release on go 1.18

---

pkg/config/config.go
pkg/config/profile.go
pkg/config/profile_livemode.go
pkg/samples/samples.go

r? @
- redact livemode values from existing configs
- rename publishable keys to fix the `stripe config --list --project-name <project_name>` issue; viper has a limit on the key name length
- return `login is required` error when livemode keys are not present in the secure storage. this will force users to log in even when they have old livemode key values in existing configs
- add ability to remove livemode values from secure storage

DX-7509: redact livemode values in existing configs

---

pkg/config/config.go
pkg/config/profile.go
pkg/config/profile_livemode.go

show warning for old livemode values

---

pkg/proxy/proxy.go

append query from registered webhook endpoint to the forward-to url
`stripe listen --load-from-webhooks-api --forward-to localhost:5000`

RUN_DX-1388: append query from webhook endpoint if exists

---

pkg/fixtures/triggers/checkout.session.async_payment_succeeded.json

I noticed that the `checkout.session.async_payment_succeeded` fixture is identical to its failure counterpart minus the expected error. This means one of those will always fail to trigger depending on the account. I updated the fixture to use US payment methods.
Before:
```
➜  stripe-cli git:(master) ✗ stripe-workspace trigger --log-level=debug  checkout.session.async_payment_succeeded 
Fixture: Setting up fixture for: checkout_session
Running fixture for: checkout_session
Trigger failed: Request failed, status=400, body={
"error": {
"message": "The payment method type provided: bacs_debit is invalid. Please ensure the provided type is activated in your dashboard (https://dashboard.stripe.com/account/payments/settings) and your account is …
```

Updating checkout.session.async_payment_suceeded with US payment method

---

pkg/fixtures/triggers/invoice.created.json
pkg/fixtures/triggers/invoice.finalized.json
pkg/fixtures/triggers/invoice.paid.json
pkg/fixtures/triggers/invoice.payment_action_required.json
pkg/fixtures/triggers/invoice.payment_failed.json
pkg/fixtures/triggers/invoice.payment_succeeded.json
pkg/fixtures/triggers/invoice.updated.json

r? @tomer-stripe @vcheung-stripe 
Fix Invoice fixtures to properly work for the latest API version. There's a breaking change that doesn't pull existing pending invoice items by default and so all fixtures needed to be fixed to pass `pending_invoice_items_behavior: 'include'` to ensure it works on all API versions.
Additionally, move away from Token/Card as those have been deprecated for years and use PaymentMethod directly everywhere.

Fix Invoice fixtures to work with latest API version

---

pkg/fixtures/triggers/checkout.session.async_payment_failed.json
pkg/fixtures/triggers/checkout.session.async_payment_succeeded.json
pkg/fixtures/triggers/checkout.session.completed.json

Fix Checkout related fixtures to not use legacy line items path as it doesn't work on the latest API version.

Fix Checkout related fixtures to not use legacy line items path

---

pkg/plugins/plugin.go
pkg/plugins/utilities.go

- remove `unmanaged` field in plugin manifest
- remove old plugin versions after installation by archive completes
- ignore directories in archives

clean up duplicated plugin versions from archive install

---

pkg/plugins/utilities.go

```
st-etsai1:stripe-cli etsai$ stripe-dev plugin install --archive-path ~/Downloads/stripe-cli-next-v0.2.1-macos-all.tar.gz
extracting tarball at /Users/etsai/Downloads/stripe-cli-next-v0.2.1-macos-all.tar.gz...
✔ extracted manifest 'manifest.toml'
✔ extracted plugin 'stripe-cli-next'
✔ updated '/Users/etsai/.config/stripe/plugins.toml' with a release entry for 'stripe-cli-next'
✔ installation complete.
```
```
st-etsai1:stripe-cli etsai$ sc-curl https://artifactory.stripe.build/artifactory/thirdparty-managed/stripe-cli/plugins/stripe-cli-next/stripe-cli-next-v0.2.1-macos-all.tar.gz/01aba21d7d64c44afba936a71379fb40c45f00023168fa35c3c952d958bf87fc/stripe-cli-next-v0.2.1-macos-all.tar.gz | stripe-dev plugin install -
% Total    % Received % …
```

handle multiple release versions in the archived manifest

---

pkg/fixtures/triggers/payout.created.json
pkg/fixtures/triggers/payout.updated.json

r? @
Updating payout.created and payout.updated fixtures to include a PaymentIntent creation that bypasses pending balance to ensure there is available balance for these triggers to succeed.
Tested locally for both triggers and works great!

Payout.* fixtures updates

---

pkg/fixtures/triggers/charge.captured.json

Updating the charge.captured trigger to create a PaymentIntent instead of creating a Charge. 
Tested locally and looks good:

Updating charge.captured to use PI instead of Charge

---

pkg/websocket/client.go

r? @bernerd-stripe 
I noticed that we were seeing an decrease in ACKs as the # of event we sent from the backend server went up. I was able to find logs from the CLI side that indicated that the read deadline was exceeded: 
```
[Thu, 15 Sep 2022 12:04:31 PDT] DEBUG websocket.Client.Close: read error: read unix ->/Users/gracegoo/.stripeproxy: i/o timeout
```
When we have a lot of real messages incoming, the backend prioritizes those over the pongs. However, the CLI was only re-setting the deadlines on Pongs and not incoming messages. This change moves the deadline setting logic to within the read loop. 
I reproduced this by disabling pongs from the server.
With no incoming message, we establish connection at 12:04:21 and get a read error at 12:04:31 
With an …

Setting ReadDeadline every time we receive an incoming message

---

pkg/cmd/plugin/install.go
pkg/cmd/plugin/upgrade.go

cc @stripe/developer-products @htheodore-stripe 
Add `--api-base` flag to `stripe plugin install` and `stripe plugin upgrade` to help with local plugin development.

Add api-base flag to plugin commands

---

pkg/cmd/login.go
pkg/cmd/root.go
pkg/login/client_login.go
pkg/login/client_login_test.go

Before, when running `stripe login`, the CLI would wait for user input to open the browser, then try to retrieve keys. This caused an issue where if you went to the auth page directly without input, the CLI would not retrieve keys. We fix this by polling for keys concurrently while waiting for input.

Poll for API keys earlier in the login flow

---

go.mod
go.sum
pkg/config/config.go
pkg/config/config_livemode.go
pkg/config/config_livemode_arm64.go
pkg/config/profile.go
pkg/config/profile_livemode.go
pkg/config/profile_livemode_arm64.go

- restore storing livmode api keys by OS default credential management app
- store livemode api keys by `add-generic-password` for macOS arm64, due to CGO incompatibility with keying library

Re-enable livemode key management

---

pkg/cmd/plugin_cmds.go
pkg/cmd/plugin_cmds_test.go

Fixes an issue where the host passes the wrong args to plugins. This issue affected commands like:
- `stripe help plugin_name`: would panic
- `stripe --log-level trace plugin_name`: would exit with unknown command

Fix arg passing to plugin processes

---

.goreleaser/linux.yml

Users reported not being able to run the stripe binary that comes in the docker image: https://github.com/stripe/stripe-cli/issues/993.
For some reason, I wasn't able to reproduce this with either version on my WSL2 setup, but I could verify that the 12.4.1 version would always pull the x86_64 and the 1.13.0 would always pull ARM. I think we just end up with whatever version we last pushed to the image since they share the same template. 
This adds the arch to the image template so we can have both instances. I would hope that grabbing just `stripe/stripe-cli` would grab the latest and correct arch automatically, but I'll have to test this after we run the release.

Updating image template to include arch

---

pkg/cmd/plugin/upgrade.go
pkg/plugins/utilities.go
pkg/plugins/utilities_test.go

Previously, we'd fetch the remote plugin manifest and write it the local config. this caused issues if the remote manifest was invalid (for example, if it was empty), since the install step would fail, but it would break the `stripe plugin upgrade` and `stripe plugin install` commands from then on. 
This PR changes it so that:
- when running `install`, it will fail fast with a useful error
- when running `upgrade`, it will log that we couldn't fetch the remote manifest, so we'll upgrade based off of the local `plugins.toml`

fix: do not overwrite local plugin manifest if fetched manifest is invalid

---

.github/workflows/release.yml
.goreleaser/linux.yml

In this [PR](https://github.com/stripe/stripe-cli/pull/999), I included the arch in the image template. This lets us pull the correct version when specifying the image with the arch like so:
```
➜  stripe-cli git:(gracegoo-docker-manifest) ✗ docker images
REPOSITORY          TAG             IMAGE ID       CREATED          SIZE
stripe/stripe-cli   latest-amd64    3bdd1fd31953   11 seconds ago   29.1MB
stripe/stripe-cli   v1.13.1-amd64   3bdd1fd31953   11 seconds ago   29.1MB
stripe/stripe-cli   latest-arm64    42447b0cbc8a   14 seconds ago   28.2MB
stripe/stripe-cli   v1.13.1-arm64   42447b0cbc8a   14 seconds ago   28.2MB
➜  stripe-cli git:(gracegoo-docker-manifest) ✗ docker image inspect 3bdd1fd31953 | jq '.[].Architecture '
"amd64"
➜ …
```

Add docker manifest

---

.goreleaser/linux.yml

The last update causes the release step to fail while building the docker image: https://github.com/stripe/stripe-cli/actions/runs/3465880982
Not entirely sure why... but there may be a mismatch in the specific ARM version we are requesting vs. the one that we actually create. The posts below suggest omitting it: 
https://github.com/moby/moby/issues/42158 
https://github.com/docker/for-linux/issues/1170
Local building of the images seem to work on my local machine so I am unable to verify: 
```
stripe-cli git:(gracegoo-remove-platform-tag) goreleaser release -f .goreleaser/linux.yml --rm-dist --snapshot
• starting release...
• loading config file                              file=.goreleaser/linux.yml
• loading environment variables
• …
```

Removing the platform tag

---

.github/workflows/release.yml
.github/workflows/test-gorelease.yml
.github/workflows/test-snapshot.yml
.goreleaser/linux.yml

Using docker's [buildx](https://docs.docker.com/build/buildx/install/) builder so we can set the platform images. 
Also added a test-snapshot workflow that will only trigger for updates to the goreleaser.

Adding buildx to docker image building

---

pkg/cmd/samples/create.go
pkg/rpcservice/sample_configs.go
pkg/rpcservice/sample_create.go
pkg/rpcservice/sample_create_test.go
pkg/samples/create.go
pkg/samples/list.go
pkg/samples/os.go
pkg/samples/os_test.go
pkg/samples/samples.go
pkg/samples/samples_test.go
rpc/commands_grpc.pb.go

Refactors the `samples` command so that the code can be re-used/configured via plugin.
Specifically
* I renamed the `Samples` struct to `SampleManager` as identifier `samples` was referring both to the package and to an instance of `Samples` which I found confusing.
* I gave `SampleManager` a constructor helper, `NewSampleManager` with a default initialization, rather than having it initialized directly everywhere.
* I changed the `Create` and `GetSampleConfig` functions to be methods with a `SampleManager` receiver, so that they are more configurable.
* I refactored `ConfigureDotEnv` into `SampleManager.ConfigureDotEnv` (which can be given a custom implementation, now that it's on the struct), and `WriteDotEnv`.
* I introduced a …

Refactor `samples.go` to be more configurable

---

pkg/fixtures/triggers/checkout.session.async_payment_failed.json
pkg/fixtures/triggers/checkout.session.async_payment_succeeded.json

r? @
Updates the checkout.session.async_payment_failed.json and checkout.session.async_payment_succeeded.json fixtures so that it works for a larger set of our merchants who are either in US or Europe instead of just UK merchants.
https://admin.corp.stripe.com/team-run/boards/RUN_DX/preview/RUN_DX-1652
Safe to revert unless specified otherwise

fix triggers

---

pkg/fixtures/triggers/issuing_authorization.request.json
pkg/fixtures/triggers/issuing_card.created.json
pkg/fixtures/triggers/issuing_cardholder.created.json

With the release of tighter restriction on cardholder terms acceptance and first/last name requirements, this PR fixes issuing related fixtures so that issuing-related triggers will work again.

Have issuing fixtures pass individual names and terms acceptance

---

pkg/cmd/listen.go
pkg/cmd/logs/tail.go
pkg/logtailing/tailer.go
pkg/proxy/proxy.go
pkg/requests/base.go
pkg/requests/webhook_endpoints.go
pkg/rpcservice/listen.go
pkg/rpcservice/logs_tail.go
pkg/samples/samples.go
pkg/stripe/client.go
pkg/stripeauth/client.go
pkg/stripeauth/client_test.go

r?
This is the initial phase of a refactor to update CLI packages to depend on a client interface instead of accepting keys, URLs, etc. and constructing their own clients.
* Introduces `stripe.RequestPerformer` interface, implemented by `*stripe.Client`
* Updates `proxy` to accept `stripe.RequestPerformer` instead of directly accepting a key and base URL
* `listen` and `logs` commands construct a client to provide to the proxy
* Add `MakeRequestWithClient` to `requests.Base` to support usage with an already-constructed client

Introduce Stripe client interface for proxy

---

pkg/websocket/messages.go
pkg/websocket/messages_test.go

r?
Instead of always skipping structured messages of an unknonw type with a generic log message, the websocket client will provide them to the configured handler in the Unknown field of the IncomingMessage type.
Existing message handlers already defensively handle unexpected message types by explicitly checking for msg.WebhookEvent or msg.RequestLogEvent.

Add websocket.UnknownMessage

---

pkg/proxy/proxy.go
pkg/proxy/proxy_test.go
pkg/proxy/webhook_event_processor.go

r?
`proxy.Proxy` remains the primary entrypoint for setting up a listen session, in particular handling validation and processing of direct user inputs. This PR, however, extracts the core webhook processing logic (parsing, filtering, notifications, forwarding, etc.) into `WebhookEventProcessor`.

Extract WebhookEventProcessor from Proxy

---

pkg/config/profile.go
pkg/config/profile_test.go

https://jira.corp.stripe.com/browse/DX-8171
We want to clear the profile before writing to it, otherwise stale profile data can linger around. For example, if you login to a new account that doesn't have a business name set, your display name in the Stripe CLI will be innaccurate.

fix: remove all profile keys when logging into a new account

---

pkg/git/editor_test.go

r? @charliecruzan-stripe 
I set up the stripe CLI for the first time on my laptop today and ran `make test` as suggested by the README. Everything passed except for one test, which tests that when an editor preference is not given to git that it uses a preference from the current environment (the `EDITOR` variable). I keep `EDITOR` set to `vim` on my system, which causes the test to fail as it wants `vi` explicitly.
My gut feeling is that this test isn't really covering functionality that's unique to the Stripe CLI, and is instead covering how git's editor defaults are computed. I thought about setting `EDITOR` in the test's setup, which would have to change based on `runtime.GOOS`. Then I figured that we might just be better off without the test at all, if …

Removes test of default editor passthrough from git

---

pkg/cmd/root.go
pkg/cmd/status.go

```
$ stripe-dev help
The official command-line tool to interact with Stripe.
Usage:
stripe [command]
Webhook commands:
listen                             Listen for webhook events
trigger                            Trigger test webhook events
Stripe commands:
logs                               Interact with Stripe API request logs
Resource commands:
get                           Quickly retrieve resources from Stripe
charges                       Make requests (capture, create, list, etc) on charges
customers                     Make requests (create, delete, list, etc) on customers
payment_intents               Make requests (cancel, capture, confirm, etc) on payment intents
...                           To see more resource commands, …
```

hide status command

---

pkg/fixtures/triggers/checkout.session.async_payment_succeeded.json

r? @
Fix trigger checkout.session.async_payment_succeeded to use SEPA Debit
Fixes https://github.com/stripe/stripe-cli/issues/1104
The trigger was changed a few months ago in https://github.com/stripe/stripe-cli/pull/929 but this was done incorrectly. It uses a card to confirm the Checkout Session which would never cause that Event to be triggered. We switched away from BACS Debit that is not supported in most countries but we still broke the trigger. I'm switching to SEPA Debit which is supported in a lot of countries (though not all) making the trigger work again.
Note that a future improvement would be for the CLI to dynamically pick the right currency and payment method type to trigger that Event but this would be a substantial redesign of triggers.

Fix trigger checkout.session.async_payment_succeeded to use SEPA Debit

---

pkg/fixtures/triggers/charge.disputed.created.json
pkg/fixtures/triggers/charge.failed.json
pkg/fixtures/triggers/charge.refund.updated.json
pkg/fixtures/triggers/charge.refunded.json
pkg/fixtures/triggers/charge.succeeded.json

r? @
Move all charge.* triggers to use the PaymentIntents API so that it's clearer that this is the canonical integration path overall.
The one small downside is that you can't use the CLI anymore to get a Charge object without a PaymentIntent and with a legacy Card object. I think that trade-off is worth it since you can always make your own triggers if you need a legacy behavior.

Move all charge.* triggers to use the PaymentIntents API

---

pkg/config/profile.go

It's possible to get into a state where the values stored in the config file do not equal the values that viper has in memory. When this happens, if we call `.WriteConfigField`, viper will write _other_ values besides the one we are explicitly passing in, causing unforeseen behavior and very difficult to track down bugs. This change makes it so that viper reads from the current config file, then sets the key we are explicitly trying to override, then writes to the file.

fix: restrict WriteConfigField to atomic writes

---

pkg/fixtures/triggers/charge.disputed.created.json
pkg/fixtures/triggers/charge.failed.json
pkg/fixtures/triggers/charge.refund.updated.json
pkg/fixtures/triggers/charge.refunded.json
pkg/fixtures/triggers/charge.succeeded.json
pkg/fixtures/triggers/payment_intent.amount_capturable_updated.json

Add required `payment_method_types` for multiple triggers to work with the latest API version
Without it, the latest API version enables "Dynamic Payment Methods" which expects a `return_url` by default for hosted UIs. Forcing `payment_method_types` is simpler here as we hardcode a `payment_method` id.

Add required payment_method_types for multiple triggers to work with the latest API version

---

pkg/cmd/samples/create.go

r? @
When you do "stripe samples create" it uses `promptui.Select` which [defaults](https://pkg.go.dev/github.com/manifoldco/promptui#Select) to only showing 5 options. We have 7 official SDKs, so many of the stripe samples have 7 options. Why not just show all of them? It's sometimes hard to spot that little arrow that indicates that you're able to scroll, so at first I didn't think the stripe sample had support for go or .NET, but it does:
Tested locally:
Some samples have more than 7 it's true (this one has a "node-typescript" option) but let's put at least the basic versions of the 7 official libraries above the fold.

stripe samples: show 7 server options, not 5

---

pkg/spec/spec.go

r? @
We are documenting Webhook events in OpenAPI spec now. Without this annotation the generation (`go generate ./..`) fails.

Teach CLI to tolerate x-stripeEvent metadata

---

pkg/config/profile.go
pkg/config/profile_test.go

https://jira.corp.stripe.com/browse/RUN_DX-2185
if a merchant manually overrides the authorization by passing the api-key flag or has the api key env var set, we can't be sure the experimental headers are correct so we should ignore them

fix: bail out of experimental request signing early if api key is overridden

---

pkg/config/profile.go

Fixes auth-loop on Linux/Gnome systems.
Thanks @ksullivan
See also
https://github.com/GNOME/gnome-keyring/blob/f24e374/daemon/dbus/gkd-secret-util.c#L111 for root-cause
r? @
- Previously, users on Linux/Gnome were stuck in an auth loop and unable to use the Stripe CLI _at all_ for anything live mode related. This is because of a bug in the upstream 99designs keyring module (which I think https://github.com/99designs/keyring/pull/90 would've fixed if it was pulled). We work around Gnome's encoding logic and 99designs' handling logic by using a simpler keychain name, without spaces.
- If pulled, this is likely to require some users who already have credentials in the previously-named keychain to need to re-authenticate.

Implement suggested fix from #1013

---

pkg/parsers/parsers.go
pkg/parsers/parsers_test.go

r? @
Fix a bug in fixture param parsing. If a param in your fixture is an array of objects, and one of these objects itself has an object, then we were parsing it incorrectly.
For example, if you have
```
"custom_fields": [
{
"label": {
"custom": "First Name",
"type": "custom"
}
}
]
```
We would expect to get
```
custom_fields[0][label][custom]=First Name
custom_fields[0][label][type]=custom
```
But we were instead getting
```
custom_fields[0][label][0][custom]=First Name
custom_fields[0][label][0][type]=custom
```
The problem was we were passing down the root array's `index` into each recursive call to the parser when we only want to pass it down one level.

Fix fixture param index bug

---

pkg/requests/ids.go

Hi Stripe!
When I was using the CLI to retrieve an invoice item by ID, I tried the following:
```
stripe get ii_im_an_invoice_item_id
```
This resulted in the following error:
```
{
"error": {
"message": "Unrecognized request URL (GET: /v1/invoice_items/ii_im_an_invoice_item_id). Please see https://stripe.com/docs or we can help at https://support.stripe.com/.",
"type": "invalid_request_error"
}
}
```
Looking at the documentation for invoice items it seems the URL has a typo as it should be `invoiceitems` instead of `invoice_items`: https://docs.stripe.com/api/invoiceitems. I changed the `ids.go` file that maps each ID to the corresponding URL as I effectively found it was mapping to `invoice_items`. Now, running the command shown above …

[Bug] Fixes #1158 bad invoice items URL

---

pkg/cmd/listen.go

r? @
Besides exiting programs on SIGTERM/ctrl+c, it's common to exit on closing stdin/ctrl+d.

cmd/listen: Exit when stdin is closed

---

pkg/cmd/listen.go

This reverts commit 531ccfb14c0c3442a20f15fe53dd36c4e60636a0.
r? @
Fixes https://github.com/stripe/stripe-cli/issues/1159

Revert "cmd/listen: Exit when stdin is closed (#1155)"

---

.github/workflows/test.yml
Makefile

r? @
We were using an old version of arduino/setup-protoc that didnt support ARM architecture for macos, which I suppose the macos-latest runners just started using, so this began failing. After upgrading, we hit another error related to diffing, and https://github.com/golangci/golangci-lint/issues/3087 pointed me to installing diffutils which worked

update setup-protoc from v1 to v3

---

.github/workflows/install-test.yml
scripts/install-test.sh

or
Adds a new Github Action that acts as a smoke test for all of our package manager install cases. This will install Stripe and run `stripe version` after:
- installing with homebrew
- installing with apt
- installing with scoop
- installing with yum
- running in the docker image
This will run once an hour, and also whenever a new tag is pushed. If it fails, this is a strong indicator that something broken in the installation flow and this should help us catch it early. To avoid noise, there's retry logic.

add action to test package manager installs

---

pkg/config/profile.go
pkg/config/profile_test.go

This removes the items from the keychain on login. This ensures that the values don't get out of sync with the values in the local configuration.

Delete keychain item on login

---

.github/workflows/test.yml
Makefile

Fix an issue where golangci-lint couldn't be installed on windows in CI. We use the golangci-lint github action as recommended by https://golangci-lint.run/welcome/install/#ci-installation.

Use golangci-lint github action

---

pkg/cmd/samples/create.go
pkg/samples/create.go
pkg/samples/samples.go
pkg/validators/validate.go

Samples were downloaded without .env file configured if the user is not logged in. The instruction to set up the .env file was not clear. We will configure .env file with test pub key placeholder and ask user to update it manually after.
```
$ stripe samples create starter
✔ Finished downloading
✔ Selected server: node
✔ Files copied
✔ Project configured
You're all set. To get started: cd starter
$ more starter/server/.env
STATIC_DIR="../client"
STRIPE_PUBLISHABLE_KEY="pk_test_51Of62wKYULnmyk0cBSrGl1xAx5l8tgArWiuu7vyXwapv6raNDE3ZWAb2cmKLEHJZxCnEMABHHXAyw04kuxXsqTWr00wOe2XCGG"
STRIPE_SECRET_KEY="rk_test_[redacted]"
STRIPE_WEBHOOK_SECRET="whsec_[redacted]"
```
```
$ stripe samples create starter
✔ Finished downloading
✔ Selected server: node …
```

Create .env file with pub key placeholder

---

pkg/login/client_login_test.go

Fix tests that fail locally on running `make test`. In https://github.com/stripe/stripe-cli/pull/1198, we need the keyring library on login, whereas we didn't before. The `InitConfig()` function initializes the keyring object.

Init config in login tests

---

pkg/login/links.go

Posts the `client_version` of the Stripe CLI to the backend on login. This allows us to more easily verify if the client is supported before continuing the login flow. This value will be:
- semver for future versions of the CLI (whenever this is released so probably >=1.20.1)
- nothing for current and previous versions (<1.20.1)
- `"master"` when the source code is run directly with `go run` or the binary is built from source

Send client version on login

---

pkg/config/profile.go

This fixes the `No directory provided for file keyring` issue when trying to run `stripe login` on WSL. On that system, there may not be a keyring backend, so we fail open to avoid blocking the login flow from completing.
I verified this on Ubuntu 22.04.4 LTS. Our unit tests actually catch this when running `make test` on this platform, so I also made sure those pass. We should consider ways to handle catching errors like this before they make it into a release.

On `stripe login`, fail open when interacting with the keyring

---

.github/workflows/install-test.yml

r? @
The github action isn't maintained and doesn't have a lot of features, let's just use Pager Duty CLI instead. This makes it so that the title of the pagerduty alert isn't a very long and confusing string plus url (plus my name, which im not a super big fan of 😄 ). Hopefully this will make this page a lot clearer to the runner

[actions] use pagerduty CLI to create alert

---

pkg/websocket/client.go
pkg/websocket/client_test.go

This change solves a deadlock that can happen in `stripe listen` when the underlying websocket connection closes or is reconnecting while the websocket client is attempting to send a message. The deadlock happens when the `writePump` has a message to send:
```go
for {
select {
case outMsg, ok := <-c.send:
```
runs into an error trying to send the message because the connection has been closed for one reason or another:
```go
err = c.conn.WriteJSON(outMsg)
if err != nil {
```
and attempts to re-queue the message it was going to process:
```go
// Requeue the message to be processed when writePump restarts
c.send <- outMsg
```
`c.send` is unbuffered, and only read from in this select. Sending messages to `c.send` in the same block that processes reads from …

Fixes shutdown deadlock in websocket client

---

pkg/spec/spec.go

r? @
Fixes failures in `openapi` CI that updates stripe-cli: https://github.com/stripe/openapi/actions/runs/10638892098/job/29495772839
We recently added a `x-stripeMostCommon` custom property to the OpenAPI spec, and apparently stripe-cli is very picky about unknown fields when unmarshalling the openapi spec.

Add x-stripeMostCommon

---

pkg/config/config.go
pkg/websocket/client.go

r? @fhats-stripe 
Adds logs to some blind spots in the websocket client. The goal is to help debug a somewhat rare deadlock in the listen command when its automatically restarting a connection after the reconnect interval has passed.
I was able to reproduce the deadlock by manually setting a short time to reconnect on the `stripe listen` command (around 3s), and in parallel triggering events in a loop using `stripe trigger`.
After a few minutes, the `stripe listen` command ran into a deadlock, at which point I attached a delve debugger to see that it was locked on the `writePump` goroutine sending a message to the `notifyClose` channel: 
https://github.com/stripe/stripe-cli/blob/5ce3aba721970df00229725e7db344e4f05c3dff/pkg/websocket/client.go#L495
The …

Add more logging to websocket client and attempt to fix deadlock in stripe listen

---

.github/workflows/release.yml

r? @charliecruzan-stripe 
The `release` workflow recently started failing to publish releases [0] due to a lack of permissions. We need to explicitly define the permissions needed in the YAML file -- other permissions that are not included are implicitly set to `none` [1].
[0] https://github.com/stripe/stripe-cli/actions/runs/10712343543/job/29744080418
[1] https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions

Set permissions in release workflow

---

pkg/fixtures/triggers/payment_method.detached.json

r? @charliecruzan-stripe 
Fixes a typo in the fixture to detach a PaymentMethod, and also removes the `customer` parameter because it's not needed [0].
Built and tested locally:
```
$ ./stripe trigger payment_method.detached
Setting up fixture for: customer
Running fixture for: customer
Setting up fixture for: payment_method_attach
Running fixture for: payment_method_attach
Setting up fixture for: payment_method_detach
Running fixture for: payment_method_detach
Trigger succeeded! Check dashboard for event details.
```
[0] https://docs.stripe.com/api/payment_methods/detach

Fix stripe trigger payment_method.detached

---

.github/workflows/install-test.yml
scripts/install-test.sh

r? @
This can flake occasionally due to network flakiness or something else that **isn't** the actual install command failing, so I say we just fully ignore any failures that aren't due to the actual install step. We rerun this every hour so if we miss one hour every few days due to a network outage, idt that's a huge deal for this test specifically.
To make this clear:
before, if any action failed (which could be due to any reason- the install failing or any setup steps for the job failing) we would page
after this PR: we only trigger the alert after the install test fails 5 times for a platform. If we fail in the setup, the job will fail silently and we'll test again in an hour.
tested this manually and made sure i got paged

fix: only trigger pager duty alert if install actually fails

---

pkg/cmd/listen.go
pkg/proxy/proxy.go
pkg/proxy/v2_stripe_event.go
pkg/stripeauth/messages.go

r? @tomas-stripe 
This adds support for linking directly to an event delivery attempt in the local listener view in workbench. We pass back the `DeviceToken` now, and use that to construct the URL. Tested this locally and confirmed the URL works as expected

fix: link to thin event in local listener view

---

ARCHITECTURE.md
pkg/cmd/resource/operation.go
pkg/cmd/resources_cmds.go
pkg/cmd/root.go
pkg/cmd/root_test.go

These paths aren't supported yet, but we want to throw a helpful error until they are

fix: show pretty error when trying to create meter event stream or session

---

pkg/fixtures/triggers/v1.billing.meter.error_report_triggered.json
pkg/fixtures/triggers/v1.billing.meter.no_meter_found.json

https://docs.google.com/document/d/1wznFRwI90rgKjzW6IyYzYFK91Ms5sjMX3434AQ2hdOI/edit#heading=h.hze9u5lv7gvp

fix: use meter-events.stripe.com instead of events.stripe.com

---

pkg/cmd/listen.go
pkg/fixtures/triggers/v1.billing.meter.error_report_triggered.json
pkg/fixtures/triggers/v1.billing.meter.no_meter_found.json
pkg/proxy/v2_stripe_event.go

r? @
Need to add the same event handling code that we use for snapshot events + update the fixtures

Small connect fixes for billing meters

---

pkg/cmd/serve.go

r? @
`http.ListenAndServe` doesn't use specifically localhost unless you set it in the address. I verified this with `netstat -an | grep 4242`.

use localhost for serve command

---

pkg/cmd/resource/operation.go

Gives clarity when operating on connected accounts. there are 3 APIs that will result in showing this:
- DELETE `/v1/accounts/:id`
- DELETE `/v1/accounts/:id/external_accounts/:id`
- DELETE `/v1/accounts/:id/persons/:id`
```
❯ stripe-dev accounts delete acct_123123123
This command will be executed on the account with the following details:
> Mode: Test
> Account Name: Merchant's Display Name
> Connected Account: acct_123123123
Are you sure you want to perform the command: DELETE?
Enter 'yes' to confirm: 
```

fix: show connected account ID if deleting a connected account's resource

---

pkg/cmd/resource/alias.go
pkg/cmd/resource/resource.go
pkg/cmd/resources.go
pkg/cmd/resources_cmds.go
pkg/cmd/resources_test.go
pkg/cmd/root_test.go
pkg/gen/gen_resources_cmds.go

This change adds the ability to alias resources so that they are renamed in the CLI's resource list. This allows resources to effectively be renamed, while preserving backwards compatibility by supporting the "principle" (e.g. OpenAPI spec) name but hiding that name from help text output.
The first consumer of this feature is invoice line items. Today, the CLI supports these under the name `line_items`, which differs from how the same resource is accessed in the Stripe Shell and Workbench (there it's `invoice_line_items`). It's also just not a very descriptive name -- there's the notion of line items in at least one other API (credit notes), and not having the `invoice_` prefix separates this resource from its other invoicing siblings in …

Adds the capability to alias resource names and aliases line_items -> invoice_line_items

---

go.mod
go.sum
pkg/cmd/logs/tail.go
pkg/cmd/logs/tail_test.go

This PR adds some basic sanitization of the output of `stripe logs tail`, as elements of this output can be influenced by user input. Also adds a few tests for the behavior added.

Adds sanitization of request log data on output

---

scripts/install-test.sh

r? @ianjabour-stripe 
if we fail to install multiple times and trigger an alert, we should also set the status of the GH action to 'failed' by exiting with code 1

[actions] fail package manager action if paging

---

.github/workflows/release.yml

r? @
The latest release action fails when trying to upload to artificatory: https://github.com/stripe/stripe-cli/actions/runs/12899742651. Checking the logs reveals the publish-to-artificatory.sh script never made any request to artifcatory.
There aren't any related changes in our repo between this release ([v1.23.5](https://github.com/stripe/stripe-cli/actions/runs/12899742651)) and the last successful one ([v1.23.3](https://github.com/stripe/stripe-cli/actions/runs/12420963875)). The only difference I could find between these two was that ubuntu-latest has been updated from 22.04 to 24.04, which I confirmed in the GitHub actions logs. This pins it to the older version to confirm if this is the cause of the failure.

Downgrade release action ubuntu version

---

.goreleaser/linux.yml

r? @
Fix error releasing to docker: https://github.com/stripe/stripe-cli/actions/runs/12919228652/job/36029305762
When run locally, I now get this:
```
goreleaser release --skip=publish --clean --config ./.goreleaser/linux.yml --snapshot
• skipping announce, publish and validate...
• cleaning distribution directory
• loading environment variables
• getting and validating git state
• git state                                      commit=059befeb3a80ae37e63c84a64a8be9dde0f221c4 branch=master current_tag=v1.23.7 previous_tag=v1.23.6 dirty=true
• pipe skipped                                   reason=disabled during snapshot mode
• parsing tag
• setting defaults
• snapshotting
• building snapshot...                           version=1.23.7-next
• running before …
```

Fix goreleaser docker config

---

pkg/spec/spec.go

Support parsing oneOf and x-stripeErrors

---

pkg/fixtures/triggers/product.deleted.json

r? @
I noticed a very minor extra character typo in the `product.deleted` fixture json description.
I am unsure if it was worth adding as an issue before such a small change - apologies in advance if I should have.

fix: remove extra character typo in product.deleted fixture trigger json description

---

.github/workflows/release.yml
.github/workflows/test-snapshot.yml
.github/workflows/test.yml
.golangci.yml
Makefile
go.mod
pkg/cmd/feedback.go
pkg/cmd/listen.go
pkg/cmd/resource/terminal_quickstart.go
pkg/fixtures/triggers.go
pkg/parsers/parsers.go
pkg/proxy/proxy.go
pkg/rpcservice/middleware.go
pkg/rpcservice/middleware_test.go
pkg/samples/samples.go
pkg/terminal/p400/reader_methods.go
pkg/terminal/p400/reader_methods_test.go
pkg/terminal/quickstart_p400.go

Update to go 1.24.1
* bumps all our build/ci to 1.24 as well
* updated golangci to the most incremental version that supports go1.24
* there's a bunch of changes to string printing, this is a new pattern that go is enforcing (basically passing things into `%s` instead of directly)

Update golang 124

---

pkg/cmd/listen.go

r? @
The CLI listen command isn't supported by orgs so add a more explicit error when a user tries to run it with an org API key.
```
➜ ./stripe listen
[Mon, 28 Apr 2025 09:32:23 PDT] ERROR The listen command does not support organizations at this time.
```

Add an error if a user tries to run listen in an org
