stripe/stripe-cli

README.md
r? @ob-stripe 
Fixed a bug with the scoop installation command
=> Fix the scoop installation command

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/feedback.md, .github/PULL_REQUEST_TEMPLATE
r? @ob-stripe @mg-stripe @romain-stripe @trag-stripe 
I added a few templates to provide more structure for feedback on the cli.
=> Add more feedback templates

README.md
r? @ob-stripe @aarongreen-stripe 
Added byline for beta in the readme
=> Add beta byline in the readme file

pkg/login/client_login.go
r? @ob-stripe @romain-stripe @mg-stripe 
Add warning that keys will expire.
=> Add warning message for keys that'll expire

.travis.yml
r? @ob-stripe 
Make sure we download all dependencies in travis
=> Add pre-install commands for travis

.vscode/settings.json
r? @ob-stripe
I thought I fixed this already, but apparently not. Going to self-approve since it's a fairly trivial PR.
=> Fix VSCode settings

pkg/ansi/ansi.go, pkg/cmd/delete.go, pkg/cmd/get.go, pkg/cmd/listen.go, pkg/cmd/post.go, pkg/config/config.go, pkg/login/interactive_login.go, pkg/login/login_message.go, pkg/proxy/proxy.go, pkg/requests/examples.go, pkg/spec/spec.go, pkg/status/status.go, pkg/status/status_test.go, pkg/websocket/messages.go, pkg/websocket/request_log_messages.go
r? @ob-stripe 
A bunch of fixes for issues reported by various linters. Most of these are purely stylistic, but some were actual bugs.
=> Lint fixes

pkg/status/status.go, pkg/status/status_test.go
r? @romain-stripe @aarongreen-stripe @brandur-stripe 
=> Make the status icons more suble

.vscode/launch.json, pkg/cmd/config.go, pkg/cmd/listen.go, pkg/cmd/root.go, pkg/cmd/trigger.go, pkg/config/config.go, pkg/config/profile.go, pkg/config/profile_test.go, pkg/login/client_login.go, pkg/login/interactive_login.go, pkg/requests/base.go, pkg/requests/examples.go, pkg/requests/examples_test.go
r? @aarongreen-stripe @brandur-stripe @ob-stripe 
This creates a config command that:
1. let's users define new config options: `stripe config color off`
2. let's users list all currently set configs: `stripe config --list`
3. let's users open an editor to modify the config file: `stripe config --edit`
4. let's users remove pre-defined config fields: `stripe config --unset color`
=> Create config command that lets users modify their configs

README.md
r? @tomer-stripe @ob-stripe 
Adds the README contents for the log tailing command and supported filters.
=> README updates for log tailing command

.travis.yml
r? @ob-stripe 
Followup to #94.
=> Fix Docker publish pipeline

README.md
r? @ob-stripe 
Update `README.md` to mention Docker images
=> Update README.md to mention Docker images

api/openapi-spec/spec3.sdk.json, go.mod, go.sum, pkg/cmd/resources_cmds.go
r? @ob-stripe 
Update OpenAPI spec and all dependencies.
=> Update OpenAPI spec and dependencies

README.md
r? @ob-stripe  
Update `README.md` to document the new API request commands.
=> Document API request commands

pkg/cmd/resource/operation.go, pkg/cmd/resource/operation_test.go, pkg/cmd/resources_cmds.go, pkg/cmd/resources_cmds.go.tpl
r? @ob-stripe 
So unfortunately after merging #87 into master, API request commands were no longer working because of a conflict with #81 (I think). This is just a quick and dirty fix to get things working.
Unfortunately the current state of the code makes it very difficult to write proper tests. I want to do some refactoring and add tests soon.
=> Fix API request commands

pkg/cmd/resource/operation_test.go
r? @ob-stripe 
Add a test for operation commands.
=> Add a test for operation commands

README.md
r? @ob-stripe 
Make a few small tweaks to the readme.
=> Make some readme changes

pkg/config/profile.go, pkg/samples/samples.go
r? @ob-stripe 
Set the publishable key in the env file
=> Set publishable key when creating a sample

pkg/config/profile.go, pkg/samples/samples.go
Found a few bugs after merging the samples branch into master, fixed those here.
=> Fix a few samples bugs that happened after merging

pkg/requests/base.go
This adds a `--livemode` flag to the http and resource commands. The resource commands get them because they leverage the `Base` requests package which is where it was added.
=> Add live mode flag to the http and resource commands

pkg/cmd/listen.go, pkg/cmd/logs/tail.go, pkg/proxy/stripeevent.go, pkg/proxy/stripeevent_test.go
r? @tomer-stripe
Add `--livemode` flag to `listen` and `logs tail` commands.
=> Add --livemode flag to `listen` and `logs tail` commands

pkg/logtailing/tailer.go, pkg/logtailing/tailer_test.go
Fix hyperlinks for live mode request logs.
=> Fix links for live request logs

pkg/cmd/open.go
Conditionally open livemode dashboard links if livemode is provided.
=> Open links in livemode

pkg/cmd/samples/create.go, pkg/samples/samples.go
Wording/style changes when creating samples:
=> Change the output of creating a sample

pkg/cmd/samples/create.go
Let users provide a destination for where to create the sample
=> Let users specify where to create a sample

README.md, pkg/cmd/root.go, pkg/login/client_login.go
=> Clean up installation instructions on readme

pkg/cmd/listen.go
Avoid conflict with the `-p` for `--project-name`
=> Change listen shorthand json

pkg/requests/examples.go, pkg/requests/examples_test.go
r? @ob-stripe 
`stripe trigger` command was resulting in invalid data in the dashboard. This was due to it attempting to tokenize raw card data (test cards).
Refactored examples.go to use [test tokens](https://stripe.com/docs/testing#cards) instead and added request body checks in examples_test.go so we will catch something like this in future
=> Refactored examples.go to use test tokens instead of test card data

.gitignore, Makefile
r? @joek-stripe 
This isn't the first time we merge code, only to discover that the code fails to compile for a specific platform when we try to release a new version.
This PR ensures that we build the CLI for all supported platforms in CI, so we can catch these issues earlier.
=> Build all platforms in CI

README.md
=> Move a bunch of extra/advanced into into the wiki and link to those pages

README.md
=> Add missing closing code block

pkg/login/client_login.go
r? @mg-stripe @romain-stripe 
Explain why we having pairing codes
=> Explain the pairing code

pkg/cmd/root.go
r? @ob-stripe 
show help page when `stripe` receives an unknown command
=> display help page on unknown commands

pkg/cmd/trigger.go, pkg/requests/examples.go
r? @ob-stripe 
Adds more triggers for events:
* invoice.payment_failed
* customer.deleted
* customer.subscription.deleted
* charge.refunded
* charge.dispute.created
Fixes #196
=> Add more triggers for events

pkg/samples/list.go
r? @adreyfus-stripe @ob-stripe 
cc @stripe/dev-platform @ctrudeau-stripe @thorsten-stripe 
Add new smaples!
=> Add new samples

pkg/requests/examples.go, pkg/requests/examples_test.go
=> Minor fixes

pkg/cmd/resource/operation.go
=> Fix linting issue

README.md, go.mod, pkg/cmd/delete.go, pkg/cmd/gen_resources_cmds.go, pkg/cmd/get.go, pkg/cmd/post.go, pkg/cmd/resource/operation.go, pkg/cmd/resource/operation_test.go, pkg/cmd/resources_cmds.go, pkg/cmd/resources_cmds.go.tpl, pkg/cmd/templates.go, pkg/requests/base.go
cc @stripe/dev-platform 
All the individual PRs in this integration branch have already been reviewed and approved, so no need to review thoroughly.
=> Pass request parameters as flags instead of arguments

pkg/version/version.go, pkg/version/version_test.go
Making the version check a little more robust to hopefully reduce false positives.
=> Improve version checking for CLI version

pkg/proxy/endpoint.go, pkg/proxy/endpoint_test.go, pkg/proxy/proxy.go
Display the event ID the log lines for endpoint responses, so users know which request the response is for.
Screenshot:
Fixes #216.
=> Display event ID in endpoint responses log lines

CODE_OF_CONDUCT.md
=> Contributor Convenant

api/openapi-spec/spec3.sdk.json, pkg/cmd/resources_cmds.go
Update OpenAPI spec and regenerate commands
=> Update OpenAPI spec and regenerate commands

pkg/samples/list.go
Added a couple new samples and renamed the web card payments sample (which now including mobile versions of the sample)
=> Renamed card elements sample and added new ones

README.md
=> Add License to readme

pkg/cmd/completion.go, pkg/cmd/config.go, pkg/cmd/get.go, pkg/cmd/listen.go, pkg/cmd/login.go, pkg/cmd/logs.go, pkg/cmd/logs/tail.go, pkg/cmd/open.go, pkg/cmd/samples/create.go, pkg/cmd/samples/list.go, pkg/cmd/status.go, pkg/cmd/trigger.go, pkg/requests/base.go
r? @ob-stripe @auchenberg-stripe 
Clean up a bunch of the CLI docs and add examples
=> Clean up command docs and add examples

README.md
=> Update links to wiki in readme

pkg/cmd/root.go
r? @
Update value prop to align with overall messaging.
=> Update value prop messaging.

pkg/cmd/delete.go, pkg/cmd/get.go, pkg/cmd/listen.go, pkg/cmd/post.go, pkg/cmd/resources.go, pkg/cmd/root.go, pkg/cmd/templates.go, pkg/cmd/trigger.go, pkg/version/version.go
r? @tomer-stripe @auchenberg-stripe 
We're releasing on time 🎶 
Fixes #263.
=> We're out of beta

README.md
=> Tweaks to readme wording

README.md
r? @auchenberg-stripe @ob-stripe 
Fixes some links/typos
Fixes #283
=> Fix links/typos in readme

README.md
r? @ob-stripe @auchenberg 
Link to a small wiki about the `events resend` command
=> Link to events resend command

pkg/cmd/root.go
Fix `--color` flag so that it works as expected.
Fixes #286.
=> Fix --color flag

api/openapi-spec/spec3.sdk.json, pkg/cmd/events_list.go, pkg/cmd/resources_cmds.go
Update OpenAPI spec for new API version, and regenerate files.
=> Update OpenAPI spec and regenerate files

pkg/requests/base.go
Removes extra newline being added, kind of fixes #303
=> Remove extra new line in API requests

pkg/samples/list.go
Changing the name of the subscription sample
=> Update subscription sample

pkg/samples/list.go
r? @adreyfus-stripe 
Fix sample subscription typo!
=> Fix subscriptions sample url

pkg/cmd/config.go
Fix examples for the `config` command.
Fixes #343.
=> Fix config examples

pkg/cmd/config.go
Fix `--set` flag in `config` command.
=> Fix config --set flag

pkg/samples/list.go
=> Add connect-onboarding-for-standard sample to CLI

README.md
=> Document serve command

pkg/samples/list.go
=> Add "oxxo-payment" Stripe Sample to CLI 

pkg/cmd/fixtures.go
r? @ob-stripe 
I broke the fixtures command in #363. This fixes it.
=> Fix fixtures command

.travis.yml, scripts/publish-deb-to-bintray.sh, scripts/publish-rpm-to-bintray.sh, scripts/upload-zip-to-virustotal.sh
Automatically upload new releases to VirusTotal. I'm hoping this will let us catch issues like #379 earlier.
=> Upload Windows archives to VirusTotal

pkg/samples/list.go
Add the new https://github.com/stripe-samples/au-becs-debit-payment sample.
=> Add au-becs-debit-payment sample

pkg/samples/list.go
Add https://github.com/stripe-samples/subscriptions-with-card-and-direct-debit to samples list.
@tomer-stripe can you merge and release?
=> Add Card & Direct Debit + Subs sample

pkg/cmd/samples/create.go, pkg/cmd/samples/list.go, pkg/samples/list.go, pkg/samples/samples.go, pkg/samples/samples_test.go
Closes #393 
* Use the existing clone, cache, and pull mechanisms to get the samples list from a remote repository: https://github.com/stripe-samples/samples-list
@tomer-stripe could you review? Not a Golang expert and I'm not sure it's a robust implementation. Also `samples_test.go` is failing :(
=> Get samples list from remote repository

.golangci.yml, Makefile, pkg/cmd/listen.go, pkg/cmd/logs/tail.go, pkg/cmd/open.go, pkg/cmd/samples/create.go, pkg/cmd/samples/list.go, pkg/cmd/trigger.go, pkg/config/config.go, pkg/fixtures/fixtures.go, pkg/login/client_login.go, pkg/login/interactive_login.go, pkg/login/login_message.go, pkg/logtailing/tailer.go, pkg/logtailing/tailer_test.go
r? @ob-stripe 
cc @stripe/dev-platform @suz-stripe @thorsten-stripe (cc as a heads up)
Update the linter to the newest version
=> Update linter to newest version

pkg/proxy/proxy.go, pkg/stripeauth/client.go, pkg/stripeauth/messages.go, pkg/websocket/client.go
=> #401 Display API Version when running listen

api/openapi-spec/spec3.sdk.json, pkg/cmd/events_list.go, pkg/cmd/resources_cmds.go
r? @tomer-stripe  @ob-stripe 
Ran the Makefile script to pull in the latest api changes for resource autogen.
🌻
=> update apispec to latest

README.md
=> Fix Travis build image in README

README.md
r? @ob-stripe @auchenberg-stripe 
cc @stripe/dev-platform @ianjabour-stripe 
Points readme to new cli ref
=> Point links to CLI ref site

api/openapi-spec/spec3.sdk.json, pkg/cmd/resources_cmds.go
r? @ob-stripe 
cc @stripe/dev-platform @areagle-stripe @remi-stripe 
Update openapi spec
=> Update openapi spec (4/22/2020)

api/openapi-spec/spec3.sdk.json, pkg/cmd/resources_cmds.go
Adds support for the new Price resource.
=> Update OpenAPI spec

go.mod, go.sum, pkg/ansi/ansi.go
r? @ob-stripe 
Had to make one change to the spinner to use `time.Duration` instead of an int, everything else seems to work!
=> Update dependencies (May 2020)

api/openapi-spec/spec3.sdk.json, pkg/cmd/resources_cmds.go
=> Update CLI resource commands

.github/PULL_REQUEST_TEMPLATE
Update the cc with developer-products instead of dev-platform
=> Update pr template with the right team

api/openapi-spec/spec3.sdk.json, pkg/cmd/resources_cmds.go
Add support for the List SetupAttempt API that was just released
=> Update openapi to support SetupAttempt List API

pkg/requests/base.go
Fixes a typo in stripe get docs
=> DX-5488 - fixes a typo in stripe get docs

pkg/playback/http_playback_test.go, pkg/playback/http_recorder.go, pkg/playback/http_replayer.go
Cleaning up a few unused functions before start work on the Cassette DX
=> Cleanup a few unused functions

api/openapi-spec/spec3.sdk.json, pkg/cmd/events_list.go
=> Update openapi spec (November 2020)

.goreleaser.yml
cc @stripe/developer-products 
Fixes #573
=> remove postinstall script for linux

.github/workflows/release.yml
+ I tracked down all of the additional environment requirements for the Bintray / VirusTotal scripts.
+ Tiny cleanup tweaks to grammar
+ added some safeguards – more robust tag filter and conditional for branch name
=> add needed vars and tools for bintray/virustotal scripts

.github/workflows/release.yml
=> remove master check for release action

api/openapi-spec/spec3.sdk.json, pkg/cmd/events_list.go, pkg/cmd/resources_cmds.go
cc @stripe/developer-products @suz-stripe @pepin-stripe @cjavilla-stripe 
Updating the CLI with the most recent spec
=> Update CLI with most recent spec

.github/workflows/release.yml, .goreleaser/linux.yml, scripts/upload-zip-to-virustotal.sh
cc @stripe/developer-products @tjfontaine-stripe @pepin-stripe 
* Log in to docker (per https://github.com/goreleaser/goreleaser-action/issues/235)
* Update docker id (per https://goreleaser.com/deprecations#dockerbinaries)
* Wrap the windows curl command
=> Login to docker and try to fix virustotal curl commands

pkg/fixtures/triggers.go, pkg/fixtures/triggers/invoice.payment_action_required.json
r? @vcheung-stripe @om-stripe 
Fixes #624 -- this adds a `invoice.payment_action_required` trigger to the CLI. Tested manually:
```
➜ stripe-dev trigger invoice.payment_action_required
Setting up fixture for: customer
Setting up fixture for: invoiceitem
Setting up fixture for: invoice
Setting up fixture for: payment_method
Setting up fixture for: attach_payment_method
Setting up fixture for: pay_invoice
Trigger succeeded! Check dashboard for event details.
➜ stripe listen
> Ready! Your webhook signing secret is <foo> (^C to quit)
2021-04-08 11:02:02   --> payment_intent.payment_failed [evt_1Ie2AsByst5pquEtbRPQwb3k]
2021-04-08 11:02:04   --> customer.source.created [evt_1Ie2B6Byst5pquEtXLCejFen]
2021-04-08 11:02:04   --> payment_method.attached …
```
=> Invoice action required trigger

pkg/cmd/root.go, pkg/config/config.go, pkg/proxy/proxy.go, pkg/websocket/client.go
r? @pepin-stripe @tjfontaine-stripe 
Add a new trace level log for tracking webhook events
=> add trace logging for webhook events

pkg/cmd/listen.go, pkg/proxy/endpoint.go, pkg/proxy/proxy.go, pkg/proxy/proxy_test.go
r? @pepin-stripe
We missed moving the endpoint response output out of Proxy and EndpointClient. To move them, we introduce some new types so the visitor can handle them properly.
This refactor incidentally enables Proxy to return endpoint responses over the channel. Perhaps stripe daemon could leverage that in the Listen method :D
=> Move endpoint response output out of Proxy and EndpointClient

pkg/fixtures/triggers.go, pkg/fixtures/triggers/quote.accepted.json, pkg/fixtures/triggers/quote.canceled.json, pkg/fixtures/triggers/quote.created.json, pkg/fixtures/triggers/quote.finalized.json
Adding fixtures for [quotes](https://stripe.com/docs/quotes). Happy to wait until we pull in the latest specs as well to merge this in.
=> Add fixtures for quotes

pkg/proxy/proxy.go, pkg/proxy/proxy_test.go, pkg/requests/webhook_endpoints.go
r? @
Updates the code so that disabled endpoints will not be hit. (https://github.com/stripe/stripe-cli/issues/723)
=> Kwu disabled endpoints

.github/workflows/release.yml
r? @acomley-stripe 
fixes build on mac with new goreleaser version
=> bump goreleaser action version to 2.8.0 for mac

pkg/cmd/feedback.go
https://jira.corp.stripe.com/browse/DX-7029
using the new CSAT form, prefill form with client data
=> new csat link

pkg/cmd/resources_cmds.go, pkg/fixtures/triggers.go, pkg/fixtures/triggers/payment_link.created.json, pkg/fixtures/triggers/payment_link.updated.json
Pulls in the latest OpenAPI spec and adds a couple of new triggers.
=> Update spec, add a couple of new triggers

pkg/cmd/logs/tail.go
r? @ianjabour-stripe 
https://jira.corp.stripe.com/browse/DX-7101
=> make error insight more visually prominent

Makefile, docs/rpc/commands.md, go.mod, go.sum, pkg/ansi/ansi.go, pkg/cmd/plugin.go, pkg/cmd/plugin/install.go, pkg/cmd/plugin/install_test.go, pkg/cmd/plugin/upgrade.go, pkg/cmd/root.go, pkg/config/config.go, pkg/plugins/config_dev.go, pkg/plugins/interface.go, pkg/plugins/plugin.go, pkg/plugins/plugin_test.go, pkg/plugins/test_artifacts/plugins.toml, pkg/plugins/test_artifacts/plugins_updated.toml, pkg/plugins/test_utils.go, pkg/plugins/utilities.go, pkg/plugins/utilities_test.go, pkg/requests/plugin.go, pkg/validators/cmds.go
cc @stripe/developer-products @htheodore-stripe 
Please see product brief for more details.
=> add phase 1 plugin support

pkg/fixtures/fixtures.go, pkg/fixtures/fixtures_test.go
The --add, --override, and --remove flags for `stripe trigger` and `stripe
fixtures` require a specific value format.
Previously, if you provided one of these flags but forgot, say, to specify the
fixture name, the CLI would panic.
Now the CLI will show a friendly error message when an invalid rewrite flag is
provided, currently handling:
```
$ stripe trigger subscription_schedule.updated --add customer.email
Invalid value for add flag (customer.email). The add flag requires a value to set (--add fixtureName:path.to.param=value).
```
```
$ stripe trigger subscription_schedule.updated --override source=tok_amex
Invalid value for override flag (source=tok_amex). The override flag requires the name of the fixture to apply …
```
=> Show friendly errors for invalid add/override/remove fixture flags

.github/workflows/release.yml, .goreleaser/linux.yml, scripts/publish-to-artifactory.sh
https://github.com/stripe/stripe-cli/issues/656
=> DX-7329: release cli binaries to jfrog

.github/workflows/release.yml, .goreleaser/linux.yml, scripts/publish-to-artifactory.sh
=> fix github action for release script

.goreleaser/linux.yml
=> fix goreleaser script

pkg/cmd/resources.go, pkg/cmd/resources_test.go
r? @
Add a test case to verify newly updated/added resource command does not conflict with existing plugin commands
=> Verify resource command does not conflict with plugin command

.gitignore
r? @ianjabour-stripe @gracegoo-stripe 
Ignore logs
=> Ignore vscode logs

.gitignore
This is also a test to see if the `codeowner-approval` checks have been removed from github.com/stripe repositories. Stripes can read [RUN_CODE-1209](https://go/RUN_CODE-1209) for more context.
=> Remove unnecessary blank line in .gitignore

pkg/fixtures/triggers/customer.subscription.created.json, pkg/fixtures/triggers/customer.subscription.deleted.json, pkg/fixtures/triggers/customer.subscription.updated.json, pkg/rpcservice/trigger_test.go
Move Subscription fixtures to Price and PaymentMethod API
=> Move Subscription fixtures to Price and PaymentMethod API

pkg/cmd/plugin/install.go, pkg/plugins/plugin.go, pkg/plugins/utilities.go
=> Install plugin by archive remote url or local path

pkg/cmd/plugin/install.go, pkg/plugins/utilities.go
=> install plugin by archive from stdout

pkg/fixtures/parsers_test.go
https://github.com/stripe/stripe-cli/issues/962
=> add test case for fixture array parser

pkg/fixtures/triggers.go, pkg/fixtures/triggers/account.application.deauthorized.json, stripe-completion.bash
r? @tomer
Add fixture for `account.application.deauthorized`
=> Add fixture for account.application.deauthorized

pkg/requests/base.go, pkg/requests/base_test.go
=> update method visibility

.goreleaser/linux.yml
Update goreleaser config to build and release for linux arm64. Will need to verify if it works with package managers.
=> Build and release for linux arm64

pkg/cmd/plugin/install.go
=> check config and plugins toml at plugin install

pkg/fixtures/fixtures.go, pkg/fixtures/fixtures_test.go, pkg/fixtures/parsers.go, pkg/fixtures/parsers_test.go
=> Make fixture structs and parser public

README.md
=> Update readme with password store setup on dockers

README.md
cc @stripe/developer-products @remi-stripe 
Add clarification around requirement of password store with Docker and replace example snippet with working example.
=> Improve docs for password store with Docker

pkg/fixtures/triggers.go, pkg/fixtures/triggers/subscription.payment_failed.json, pkg/fixtures/triggers/subscription.payment_succeeded.json
=> add triggers for subscription.payment_failed and payment_succeeded

pkg/config/profile.go
r? @vcheung-stripe
https://github.com/stripe/stripe-cli/issues/1028
=> handle empty live keys

pkg/cmd/resources_cmds.go, pkg/gen/resources_cmds.go.tpl
Reverts stripe/stripe-cli#1054
=> Revert "make add resource commands public"

pkg/config/profile.go, pkg/config/profile_livemode_arm64.go, pkg/config/profile_test.go, pkg/requests/base.go, pkg/requests/base_test.go, pkg/requests/signing.go, pkg/requests/signing_test.go
=> Request signing beta

pkg/cmd/resource/operation.go
r? @charliecruzan-stripe 
cc @stripe/developer-products @tomer-stripe
=> Add support for nested array param

pkg/cmd/resource/resource.go, pkg/cmd/resources_cmds.go
=> Fix `stripe tax settingss` command

.github/workflows/release.yml
r? @
Motivated by https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Update versions of each action

pkg/spec/spec.go
Fixes OpenAPI publishing since a new field was added to the spec.
=> Add support for deprecated field

.github/workflows/install-test.yml, scripts/install-test.sh
Update the yum install test to run on a fedora container instead of an ubuntu:18.04 container.
Tested change in a fork of the repo
=> update yum install test

pkg/cmd/plugin/install.go, pkg/plugins/utilities.go
This removes the ability to install plugins from a local archive or via URL so that you can only install plugins via `stripe plugin install <name>`.
=> Remove flags for installing plugins from archives

pkg/cmd/listen.go
=> make connect blue in listen output

pkg/fixtures/triggers/v1.billing.meter.error_report_triggered.json, pkg/fixtures/triggers/v1.billing.meter.no_meter_found.json
r? @tomas-stripe 
Want to set this to an explicit version before release
=> set stripe-version in v1 billing meter triggers

pkg/spec/spec.go
Follow up to https://github.com/stripe/stripe-cli/pull/1233/files
^ wasn't sufficient, we were still failing to update CLI
=> Add x-stripeMostCommon as a valid schema field

pkg/cmd/fixtures.go, pkg/cmd/listen.go, pkg/cmd/login.go, pkg/cmd/logs/tail.go, pkg/cmd/plugin/install.go, pkg/cmd/plugin/upgrade.go, pkg/cmd/resource/operation.go, pkg/cmd/trigger.go, pkg/requests/base.go, pkg/stripe/client.go, pkg/stripe/url.go, pkg/stripe/url_test.go
r? @
Validates that the --api-base and --dashboard-base debugging flags point to a valid domain name. This allows us to internally debug against the correct domain names.
I confirmed each command continues to work as expected.
=> Validate base URLs

pkg/cmd/listen.go
=> add thin event listen example to help text

pkg/stripe/url.go, pkg/stripe/url_test.go
=> fix: match api urls with version path

pkg/cmd/feedback.go
r? @
new output:
```
❯ stripe-dev feedback
_        _
___| |_ _ __(_)_ __   ___
/ __| __| '__| | '_ \ / _ \
\__ \ |_| |  | | |_) |  __/
|___/\__|_|  |_| .__/ \___|
|_|
We'd love to know what you think of the CLI:
* Report bugs or issues on GitHub: https://github.com/stripe/stripe-cli/issues
```
=> fix: remove broken link

pkg/cmd/resource/operation.go
r? @
previous it was enable to parse nested array param. this PR adds the support for nested array param. 
```
$ stripe checkout sessions create --success-url="https://www.example.com" --shipping-address-collection.allowed-countries="BA" --mode="payment" -d "line_items[0][price_data][currency]=USD" -d "line_items[0][price_data][unit_amount]=20" -d "line_items[0][price_data][product_data][name]=qwe" -d "line_items[0][price_data][product_data][description]=qwe" -d "line_items[0][quantity]=10"
{
"error": {
"code": "parameter_unknown",
"doc_url": "https://stripe.com/docs/error-codes/parameter-unknown",
"message": "Received unknown parameter: shipping_address_collection.allowed_countries. Did you mean shipping_address_collection?",
"param": …
```
=> handle nested array params
